"""
Apollo-like Earth-orbit -> Moon landing optimal control with CVXPY + SCP.

Main improvements over an impulsive Delta-V model
-------------------------------------------------
1) Continuous thrust vector T[k] [kN] is the control input.
2) Spacecraft mass M[k] [kg] is an optimization state.
3) Propellant is consumed from thrust magnitude using Isp.
4) Phase-dependent thrust limits, minimum throttle and gimbal cone.
5) Maximum acceleration constraint.
6) Thrust slew-rate constraint.
7) Earth parking-orbit environment.
8) Moon-relative approach/descent speed limits.
9) Lunar surface clearance, landing cone and touchdown constraints.
10) Nonlinear gravity and T/m are handled by successive convexification (SCP).

This is an educational Apollo-like model, not a historical Apollo reconstruction.
The solver uses feasibility restoration before fuel minimization to avoid premature infeasibility.
The Moon ephemeris is approximated by a circular inclined orbit and the vehicle is
represented as one equivalent spacecraft/propulsion system.

Units
-----
position     km
velocity     km/s
acceleration km/s^2
mass         kg
thrust       kN   (numerically kg*km/s^2)
time         s
"""

import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegWriter
import shutil
import subprocess
import tempfile
from pathlib import Path


# =============================================================================
# 1. CONSTANTS
# =============================================================================

MU_E = 398600.435507       # Earth GM [km^3/s^2]
MU_M = 4902.800118         # Moon GM  [km^3/s^2]
R_E = 6378.137             # Earth radius [km]
R_M = 1737.4               # Moon radius [km]
D_EM = 384400.0            # mean Earth-Moon distance [km]
G0 = 0.00980665            # standard gravity [km/s^2]


# =============================================================================
# 2. EQUIVALENT SPACECRAFT / PROPULSION MODEL
# =============================================================================

MASS_INITIAL = 48000.0     # kg at start of LEO simulation
MASS_DRY = 6000.0          # kg minimum allowable final mass

# Equivalent discarded transfer/orbital hardware before lunar powered descent.
# This keeps the 45 kN descent engine physically compatible with the landing mass.
STAGE_DROP_AT_DESCENT = 12000.0   # kg, fixed dry hardware separation (not propellant)

# Phase-specific propulsion parameters.
ISP_TLI = 421.0            # s, equivalent high-Isp Earth-departure stage
ISP_MCC = 314.0            # s, equivalent course-correction engine
ISP_DESCENT = 311.0        # s, equivalent lunar descent engine

TMAX_TLI = 1000.0          # kN
TMIN_TLI = 250.0           # kN when scheduled TLI engine is on
TMAX_MCC = 8.0             # kN
TMAX_DESCENT = 45.0        # kN
TMIN_DESCENT = 2.0         # kN during powered descent

# Maximum proper acceleration generated by propulsion.
AMAX_TLI = 4.0 * G0        # 4 g
AMAX_MCC = 0.5 * G0        # 0.5 g
AMAX_DESCENT = 1.0 * G0    # 1 g

# Gimbal half-angle around the nominal thrust/body axis.
GIMBAL_TLI = np.deg2rad(15.0)
GIMBAL_DESCENT = np.deg2rad(35.0)

# Thrust-vector slew limits [kN/s].
SLEW_TLI = 3.0
SLEW_MCC = 0.05
SLEW_DESCENT = 0.30


# =============================================================================
# 3. MISSION PHASES / TIME GRID
# =============================================================================

LEO_ALT = 185.2            # km
LEO_ALT_MIN = 175.0        # km
LEO_ALT_MAX = 200.0        # km
LEO_INCLINATION = np.deg2rad(28.5)
MOON_INCLINATION = np.deg2rad(5.145)

# Four phases:
#   A) Earth parking orbit
#   B) finite-duration TLI burn
#   C) translunar transfer / MCC
#   D) lunar powered descent
N_PARK = 24
N_TLI = 8
N_TRANSFER = 192
N_DESCENT = 90

DT_PARK = 180.0            # 3 min
DT_TLI = 30.0              # 30 s
DT_TRANSFER = 1350.0       # 22.5 min (same total transfer time, finer grid)
DT_DESCENT = 40.0          # 40 s

DT = np.concatenate([
    np.full(N_PARK, DT_PARK),
    np.full(N_TLI, DT_TLI),
    np.full(N_TRANSFER, DT_TRANSFER),
    np.full(N_DESCENT, DT_DESCENT),
])

N = len(DT)
TIME = np.concatenate([[0.0], np.cumsum(DT)])
T_TOTAL = TIME[-1]

K_TLI_START = N_PARK
K_TRANSFER_START = N_PARK + N_TLI
K_DESCENT_START = N_PARK + N_TLI + N_TRANSFER


# =============================================================================
# 4. MISSION / LANDING CONSTRAINT PARAMETERS
# =============================================================================

MAX_EARTH_INERTIAL_SPEED = 12.5       # km/s
TOUCHDOWN_SPEED_MAX = 0.005           # km/s = 5 m/s
TOUCHDOWN_HORIZONTAL_MAX = 0.0025     # km/s = 2.5 m/s
TOUCHDOWN_DOWN_TARGET = 0.0035        # km/s = 3.5 m/s downward
TOUCHDOWN_LATERAL_TARGET = 0.0015     # km/s = 1.5 m/s along-track
TOUCHDOWN_TARGET_TOL = 0.0003         # km/s = 0.3 m/s target tolerance

# Wide at the start; velocity and altitude schedules tighten the final approach.
LANDING_CONE_ANGLE = np.deg2rad(70.0)
TERMINAL_LANDING_CONE_ANGLE = np.deg2rad(35.0)
TERMINAL_CONE_START_FRACTION = 0.95
LOW_ALT_HORIZONTAL_SPEED_SLOPE = 0.0052  # (km/s) per km altitude

# Descent gate.
DESCENT_GATE_ALT_MIN = 50.0            # km
DESCENT_GATE_ALT_MAX = 500.0           # km
DESCENT_GATE_SPEED_MAX = 2.5           # km/s Moon-relative

# SCP parameters.
MAX_SCP_ITER = 22
REFERENCE_UPDATE_ALPHA = 0.55
VIRTUAL_DV_TOL = 1.0e-2                # km/s integrated virtual acceleration
TRAJECTORY_CHANGE_TOL = 10.0           # km RMS
MASS_CHANGE_TOL = 20.0                  # kg RMS


# =============================================================================
# 5. MOON MODEL
# =============================================================================

OMEGA_MOON = np.sqrt((MU_E + MU_M) / D_EM**3)
PHI_ARRIVAL = np.deg2rad(170.0)
PHI_0 = PHI_ARRIVAL - OMEGA_MOON * T_TOTAL


def moon_state(t):
    """Circular inclined Moon orbit in Earth-centered inertial coordinates."""
    theta = PHI_0 + OMEGA_MOON * t
    c = np.cos(theta)
    s = np.sin(theta)
    ci = np.cos(MOON_INCLINATION)
    si = np.sin(MOON_INCLINATION)

    r = D_EM * np.array([c, s * ci, s * si])
    v = D_EM * OMEGA_MOON * np.array([-s, c * ci, c * si])
    return r, v


# =============================================================================
# 6. GRAVITY + JACOBIAN
# =============================================================================


def point_gravity(r, center, mu):
    d = r - center
    rho = np.linalg.norm(d)
    return -mu * d / rho**3


def point_gravity_jacobian(r, center, mu):
    d = r - center
    rho = np.linalg.norm(d)
    I = np.eye(3)
    return -mu * (I / rho**3 - 3.0 * np.outer(d, d) / rho**5)


def gravity(r, t):
    r_moon, _ = moon_state(t)
    return (
        point_gravity(r, np.zeros(3), MU_E)
        + point_gravity(r, r_moon, MU_M)
    )


def gravity_and_jacobian(r, t):
    r_moon, _ = moon_state(t)

    g_e = point_gravity(r, np.zeros(3), MU_E)
    J_e = point_gravity_jacobian(r, np.zeros(3), MU_E)

    g_m = point_gravity(r, r_moon, MU_M)
    J_m = point_gravity_jacobian(r, r_moon, MU_M)

    return g_e + g_m, J_e + J_m


# =============================================================================
# 7. INITIAL EARTH PARKING ORBIT
# =============================================================================

R_LEO = R_E + LEO_ALT
V_LEO = np.sqrt(MU_E / R_LEO)
N_LEO = np.sqrt(MU_E / R_LEO**3)

r0 = np.array([R_LEO, 0.0, 0.0])
v0 = V_LEO * np.array([
    0.0,
    np.cos(LEO_INCLINATION),
    np.sin(LEO_INCLINATION),
])


def parking_orbit_state(t):
    theta = N_LEO * t
    c = np.cos(theta)
    s = np.sin(theta)
    ci = np.cos(LEO_INCLINATION)
    si = np.sin(LEO_INCLINATION)

    r = R_LEO * np.array([c, s * ci, s * si])
    v = V_LEO * np.array([-s, c * ci, c * si])
    return r, v


# =============================================================================
# 8. LANDING GEOMETRY
# =============================================================================

r_moon_final, v_moon_final = moon_state(T_TOTAL)
e_moon = r_moon_final / np.linalg.norm(r_moon_final)

# Near-side landing-site outward normal.
n_land = -e_moon

z_axis = np.array([0.0, 0.0, 1.0])
t_land = np.cross(z_axis, n_land)
if np.linalg.norm(t_land) < 1e-8:
    t_land = np.cross(np.array([0.0, 1.0, 0.0]), n_land)
t_land /= np.linalg.norm(t_land)

P_HORIZONTAL = np.eye(3) - np.outer(n_land, n_land)
r_land_final = r_moon_final + R_M * n_land
v_touch_target = (
    -TOUCHDOWN_DOWN_TARGET * n_land
    + TOUCHDOWN_LATERAL_TARGET * t_land
)


# =============================================================================
# 9. PHASE PARAMETER HELPERS
# =============================================================================


def phase_isp(k):
    if K_TLI_START <= k < K_TRANSFER_START:
        return ISP_TLI
    if K_TRANSFER_START <= k < K_DESCENT_START:
        return ISP_MCC
    if k >= K_DESCENT_START:
        return ISP_DESCENT
    return ISP_TLI


def phase_tmax(k):
    if k < K_TLI_START:
        return 0.0
    if k < K_TRANSFER_START:
        return TMAX_TLI
    if k < K_DESCENT_START:
        return TMAX_MCC
    return TMAX_DESCENT


def phase_amax(k):
    if k < K_TLI_START:
        return 0.0
    if k < K_TRANSFER_START:
        return AMAX_TLI
    if k < K_DESCENT_START:
        return AMAX_MCC
    return AMAX_DESCENT


# =============================================================================
# 10. INITIAL SCP REFERENCE
# =============================================================================


def cubic_bezier(p0, p1, p2, p3, s):
    return (
        (1.0 - s)**3 * p0
        + 3.0 * (1.0 - s)**2 * s * p1
        + 3.0 * (1.0 - s) * s**2 * p2
        + s**3 * p3
    )


def smoothstep5(s):
    """0 -> 1 with zero first/second derivative at both ends."""
    s = np.clip(s, 0.0, 1.0)
    return 10.0 * s**3 - 15.0 * s**4 + 6.0 * s**5


def smoothstep5_derivative(s):
    s = np.clip(s, 0.0, 1.0)
    return 30.0 * s**2 * (1.0 - s)**2


def make_initial_reference():
    """
    Build an SCP reference that is intentionally feasible with respect to the
    landing cone geometry and has zero Moon-relative terminal velocity.

    The reference does NOT need to satisfy the nonlinear dynamics exactly;
    virtual control handles that during the feasibility iterations.
    """
    r_ref = np.zeros((3, N + 1))
    v_ref = np.zeros((3, N + 1))
    thrust_ref = np.zeros((3, N))
    mass_ref = np.full(N + 1, MASS_INITIAL, dtype=float)

    # -------------------------------------------------------------------------
    # A) Circular LEO reference.
    # -------------------------------------------------------------------------
    for k in range(N_PARK + 1):
        r_ref[:, k], v_ref[:, k] = parking_orbit_state(TIME[k])

    # -------------------------------------------------------------------------
    # B) Finite TLI reference propagation.
    # -------------------------------------------------------------------------
    # 350 kN is enough to create a useful departure reference without forcing
    # the mass reference unrealistically close to dry mass.
    nominal_tli_thrust = 350.0  # kN

    for k in range(K_TLI_START, K_TRANSFER_START):
        dt = DT[k]
        tangent = v_ref[:, k] / max(np.linalg.norm(v_ref[:, k]), 1e-12)
        thrust_ref[:, k] = nominal_tli_thrust * tangent

        a = gravity(r_ref[:, k], TIME[k]) + thrust_ref[:, k] / mass_ref[k]

        r_ref[:, k + 1] = (
            r_ref[:, k] + dt * v_ref[:, k] + 0.5 * dt**2 * a
        )
        v_ref[:, k + 1] = v_ref[:, k] + dt * a

        mass_ref[k + 1] = mass_ref[k] - (
            dt * nominal_tli_thrust / (ISP_TLI * G0)
        )

    # -------------------------------------------------------------------------
    # C) Translunar transfer reference to a descent gate near the Moon.
    # -------------------------------------------------------------------------
    t_stage = TIME[K_DESCENT_START]
    r_moon_stage, v_moon_stage = moon_state(t_stage)

    stage_altitude = 120.0  # km
    stage_lateral = -180.0  # km

    r_stage = (
        r_moon_stage
        + (R_M + stage_altitude) * n_land
        + stage_lateral * t_land
    )

    p0 = r_ref[:, K_TRANSFER_START]
    v_depart = v_ref[:, K_TRANSFER_START]
    t0_hat = v_depart / max(np.linalg.norm(v_depart), 1e-12)
    p3 = r_stage

    chord = np.linalg.norm(p3 - p0)
    p1 = p0 + 0.20 * chord * t0_hat

    # Final Bezier tangent roughly follows Moon inertial motion so that the
    # descent gate does not begin with an enormous Moon-relative velocity.
    transfer_duration = TIME[K_DESCENT_START] - TIME[K_TRANSFER_START]
    p2_target = p3 - (transfer_duration / 3.0) * v_moon_stage
    max_p2_offset = 0.28 * chord
    d2 = p3 - p2_target
    if np.linalg.norm(d2) > max_p2_offset:
        d2 = d2 / np.linalg.norm(d2) * max_p2_offset
    p2 = p3 - d2

    t0_transfer = TIME[K_TRANSFER_START]
    tf_transfer = TIME[K_DESCENT_START]

    for k in range(K_TRANSFER_START, K_DESCENT_START + 1):
        s = (TIME[k] - t0_transfer) / (tf_transfer - t0_transfer)
        r_ref[:, k] = cubic_bezier(p0, p1, p2, p3, s)

    # Velocity for the transfer geometry. This is a reference only.
    for axis in range(3):
        v_ref[axis, K_TRANSFER_START:K_DESCENT_START + 1] = np.gradient(
            r_ref[axis, K_TRANSFER_START:K_DESCENT_START + 1],
            TIME[K_TRANSFER_START:K_DESCENT_START + 1],
            edge_order=2,
        )

    # -------------------------------------------------------------------------
    # D) Moon-relative descent reference.
    # -------------------------------------------------------------------------
    # The SAME smooth q(s) is used for altitude and lateral displacement.
    # Therefore |lateral| / altitude = 180/120 = 1.5 < tan(70 deg), so the
    # entire initial descent reference lies inside the landing cone.
    descent_duration = TIME[N] - TIME[K_DESCENT_START]
    H0 = stage_altitude
    L0 = stage_lateral

    for k in range(K_DESCENT_START, N + 1):
        s = (TIME[k] - TIME[K_DESCENT_START]) / descent_duration
        w = smoothstep5(s)
        q = 1.0 - w
        dq_dt = -smoothstep5_derivative(s) / descent_duration

        r_moon_k, v_moon_k = moon_state(TIME[k])

        rel_vec = H0 * n_land + L0 * t_land
        # Quintic position decay plus a Hermite terminal-velocity term.  The
        # latter produces a deliberate angled, moderately firm touchdown
        # instead of forcing the reference to settle vertically at zero speed.
        h11 = s**3 - s**2
        dh11_dt = (3.0 * s**2 - 2.0 * s) / descent_duration
        r_ref[:, k] = (
            r_moon_k + R_M * n_land + q * rel_vec
            + h11 * descent_duration * v_touch_target
        )
        v_ref[:, k] = (
            v_moon_k + dq_dt * rel_vec
            + dh11_dt * descent_duration * v_touch_target
        )

    # Enforce exact terminal reference state.
    r_ref[:, N] = r_land_final
    v_ref[:, N] = v_moon_final + v_touch_target
    v_ref[:, 0] = v0

    # -------------------------------------------------------------------------
    # E) Nominal thrust reference.
    # -------------------------------------------------------------------------
    # TLI reference was already set. MCC remains zero. Descent starts gently
    # and ramps up late, keeping the reference mass realistic.
    for k in range(K_DESCENT_START, N):
        s = (k - K_DESCENT_START) / max(1, N - K_DESCENT_START - 1)
        vertical = 3.0 + 18.0 * s**4
        lateral_brake = 2.0 * (1.0 - s)**2
        thrust_ref[:, k] = vertical * n_land - lateral_brake * t_land

    # -------------------------------------------------------------------------
    # F) Consistent mass reference including stage separation.
    # -------------------------------------------------------------------------
    mass_ref[:] = MASS_INITIAL
    for k in range(N):
        sigma = np.linalg.norm(thrust_ref[:, k])
        propellant = DT[k] * sigma / (phase_isp(k) * G0)
        stage_drop = STAGE_DROP_AT_DESCENT if k == K_DESCENT_START - 1 else 0.0
        mass_ref[k + 1] = mass_ref[k] - propellant - stage_drop
        mass_ref[k + 1] = max(mass_ref[k + 1], MASS_DRY + 300.0)

    return r_ref, v_ref, thrust_ref, mass_ref


r_ref, v_ref, thrust_ref, mass_ref = make_initial_reference()



# =============================================================================
# 11. SOLVER HELPER
# =============================================================================


def solve_with_available_solver(problem):
    installed = cp.installed_solvers()

    if "CLARABEL" in installed:
        problem.solve(solver=cp.CLARABEL, verbose=False)
        return "CLARABEL"

    if "SCS" in installed:
        problem.solve(
            solver=cp.SCS,
            verbose=False,
            max_iters=50000,
            eps=1e-4,
        )
        return "SCS"

    problem.solve(verbose=False)
    return "CVXPY default"


# =============================================================================
# 12. SUCCESSIVE CONVEXIFICATION
# =============================================================================

# Two-stage solve:
#   1) feasibility restoration: drive dynamics/landing slacks toward zero
#   2) fuel optimization: minimize propellant while keeping slacks near zero
FEASIBILITY_ITERS = 8
FUEL_ITERS = MAX_SCP_ITER - FEASIBILITY_ITERS

R_solution = None
V_solution = None
T_solution = None
M_solution = None
SIGMA_solution = None
NU_solution = None
LAST_SLACKS = None


def build_scp_problem(mode, iteration, trust_multiplier=1.0, hard_landing=False):
    """Construct one convex SCP subproblem."""

    # Decision variables.
    R = cp.Variable((3, N + 1))
    V = cp.Variable((3, N + 1))
    THRUST = cp.Variable((3, N))
    MASS = cp.Variable(N + 1)
    SIGMA = cp.Variable(N, nonneg=True)
    NU = cp.Variable((3, N))

    # Soft feasibility variables for descent/terminal constraints.
    nd = N - K_DESCENT_START + 1
    S_CONE = cp.Variable(nd, nonneg=True)          # km
    S_SPEED = cp.Variable(nd, nonneg=True)         # km/s
    S_ALT = cp.Variable(nd, nonneg=True)           # km
    S_TERMINAL = cp.Variable(nd, nonneg=True)      # km/s
    S_TOUCH_POS = cp.Variable(nonneg=True)          # km
    S_TOUCH_SPEED = cp.Variable(nonneg=True)        # km/s
    S_TOUCH_HORIZ = cp.Variable(nonneg=True)        # km/s

    constraints = [
        R[:, 0] == r0,
        V[:, 0] == v0,
        MASS[0] == MASS_INITIAL,
        MASS >= MASS_DRY,
        MASS <= MASS_INITIAL,
    ]

    virtual_dv_cost = 0
    thrust_smooth_cost = 0
    propellant_cost_kg = 0

    # Do not aggressively shrink the trust region during feasibility recovery.
    if mode == "feasibility":
        trust_scale = 1.0
    else:
        fuel_iter = max(0, iteration - FEASIBILITY_ITERS)
        trust_scale = max(0.45, 0.90**fuel_iter)

    trust_scale *= trust_multiplier

    # -------------------------------------------------------------------------
    # Dynamics, thrust, propellant and phase controls.
    # -------------------------------------------------------------------------
    for k in range(N):
        dt = DT[k]
        t_k = TIME[k]

        # Linearized gravity.
        g_ref, J_ref = gravity_and_jacobian(r_ref[:, k], t_k)
        g_linear = g_ref + J_ref @ (R[:, k] - r_ref[:, k])

        # Linearized T/m.
        mbar = max(float(mass_ref[k]), MASS_DRY + 100.0)
        tbar = thrust_ref[:, k]
        thrust_acc_linear = (
            THRUST[:, k] / mbar
            - (tbar / (mbar**2)) * (MASS[k] - mbar)
        )

        acceleration = g_linear + thrust_acc_linear + NU[:, k]

        constraints += [
            R[:, k + 1]
            == R[:, k] + dt * V[:, k] + 0.5 * dt**2 * acceleration,
            V[:, k + 1] == V[:, k] + dt * acceleration,
        ]

        # Thrust norm epigraph.
        constraints += [cp.norm(THRUST[:, k], 2) <= SIGMA[k]]

        # Propellant mass flow plus a fixed dry-hardware stage separation.
        propellant_k = dt * SIGMA[k] / (phase_isp(k) * G0)
        stage_drop_k = (
            STAGE_DROP_AT_DESCENT if k == K_DESCENT_START - 1 else 0.0
        )
        constraints += [
            MASS[k + 1] == MASS[k] - propellant_k - stage_drop_k
        ]
        propellant_cost_kg += propellant_k

        # Max thrust / max proper acceleration.
        tmax = phase_tmax(k)
        amax = phase_amax(k)
        constraints += [SIGMA[k] <= tmax]
        if amax > 0.0:
            constraints += [SIGMA[k] <= amax * MASS[k]]

        # Engine phase constraints.
        if k < K_TLI_START:
            constraints += [THRUST[:, k] == 0, SIGMA[k] == 0]

        elif k < K_TRANSFER_START:
            axis = v_ref[:, k] / max(np.linalg.norm(v_ref[:, k]), 1e-12)
            constraints += [
                axis @ THRUST[:, k] >= TMIN_TLI,
                axis @ THRUST[:, k] >= np.cos(GIMBAL_TLI) * SIGMA[k],
            ]

        elif k < K_DESCENT_START:
            # MCC engine may be completely off.
            pass

        else:
            # Powered descent.  Keep the scheduled engine-on lower bound small
            # enough that feasibility is not destroyed early in SCP.
            constraints += [
                n_land @ THRUST[:, k] >= TMIN_DESCENT,
                n_land @ THRUST[:, k]
                >= np.cos(GIMBAL_DESCENT) * SIGMA[k],
            ]

        # Slew rate only inside a continuous phase, not across ignition/cutoff.
        if k > 0:
            same_tli = K_TLI_START < k < K_TRANSFER_START
            same_mcc = K_TRANSFER_START < k < K_DESCENT_START
            same_descent = k > K_DESCENT_START

            if same_tli:
                slew = SLEW_TLI
            elif same_mcc:
                slew = SLEW_MCC
            elif same_descent:
                slew = SLEW_DESCENT
            else:
                slew = None

            if slew is not None:
                dt_slew = min(DT[k - 1], DT[k])
                constraints += [
                    cp.norm(THRUST[:, k] - THRUST[:, k - 1], 2)
                    <= slew * dt_slew
                ]

        # SCP trust regions. Mass trust was intentionally removed because the
        # original artificial mass reference was a major infeasibility source.
        if k <= K_TLI_START:
            r_trust = 2000.0 * trust_scale
            v_trust = 2.0 * trust_scale + 0.5
        elif k < K_DESCENT_START:
            r_trust = 160000.0 * trust_scale
            v_trust = 8.0 * trust_scale + 1.0
        else:
            r_trust = 12000.0 * trust_scale
            v_trust = 4.0 * trust_scale + 0.5

        constraints += [
            cp.norm(R[:, k] - r_ref[:, k], 2) <= r_trust,
            cp.norm(V[:, k] - v_ref[:, k], 2) <= v_trust,
        ]

        virtual_dv_cost += cp.norm(NU[:, k], 2) * dt
        if k > 0:
            thrust_smooth_cost += cp.norm(
                THRUST[:, k] - THRUST[:, k - 1], 2
            )

    # Terminal trust region around an already landing-feasible reference.
    constraints += [
        cp.norm(R[:, N] - r_ref[:, N], 2) <= 5000.0 * trust_scale + 50.0
    ]

    # -------------------------------------------------------------------------
    # Earth parking-orbit environment.
    # -------------------------------------------------------------------------
    for k in range(N_PARK + 1):
        rhat = r_ref[:, k] / np.linalg.norm(r_ref[:, k])
        that = v_ref[:, k] / max(np.linalg.norm(v_ref[:, k]), 1e-12)
        v_circ = np.sqrt(MU_E / np.linalg.norm(r_ref[:, k]))

        constraints += [
            rhat @ R[:, k] >= R_E + LEO_ALT_MIN,
            cp.norm(R[:, k], 2) <= R_E + LEO_ALT_MAX,
            that @ V[:, k] >= v_circ - 0.50,
            cp.norm(V[:, k], 2) <= v_circ + 0.50,
        ]

    # Broad inertial speed bound.
    for k in range(K_TLI_START, K_DESCENT_START + 1):
        constraints += [cp.norm(V[:, k], 2) <= MAX_EARTH_INERTIAL_SPEED]

    # Earth collision avoidance near Earth.
    for k in range(N_PARK + 1, N + 1):
        if np.linalg.norm(r_ref[:, k]) < 50000.0:
            rhat = r_ref[:, k] / np.linalg.norm(r_ref[:, k])
            constraints += [rhat @ R[:, k] >= R_E + 100.0]

    # Moon surface avoidance, linearized about reference.
    for k in range(N + 1):
        r_moon_k, _ = moon_state(TIME[k])
        d_ref = r_ref[:, k] - r_moon_k
        d_norm = np.linalg.norm(d_ref)

        if d_norm < 80000.0:
            dhat = d_ref / max(d_norm, 1e-12)
            if k < K_DESCENT_START:
                clearance = 20.0
            else:
                frac = (k - K_DESCENT_START) / max(1, N - K_DESCENT_START)
                clearance = 20.0 * (1.0 - frac)

            constraints += [
                dhat @ (R[:, k] - r_moon_k) >= R_M + clearance
            ]

    # -------------------------------------------------------------------------
    # Descent gate.
    # -------------------------------------------------------------------------
    r_moon_gate, v_moon_gate = moon_state(TIME[K_DESCENT_START])
    r_land_gate = r_moon_gate + R_M * n_land
    delta_gate = R[:, K_DESCENT_START] - r_land_gate
    gate_altitude = n_land @ delta_gate

    constraints += [
        cp.norm(R[:, K_DESCENT_START] - r_moon_gate, 2) <= R_M + 650.0,
        gate_altitude >= DESCENT_GATE_ALT_MIN,
        gate_altitude <= DESCENT_GATE_ALT_MAX,
        cp.norm(V[:, K_DESCENT_START] - v_moon_gate, 2)
        <= DESCENT_GATE_SPEED_MAX,
    ]

    # -------------------------------------------------------------------------
    # Lunar descent with soft feasibility restoration.
    # -------------------------------------------------------------------------
    for j, k in enumerate(range(K_DESCENT_START, N + 1)):
        frac = (k - K_DESCENT_START) / max(1, N - K_DESCENT_START)
        r_moon_k, v_moon_k = moon_state(TIME[k])
        r_land_k = r_moon_k + R_M * n_land

        delta_r = R[:, k] - r_land_k
        altitude = n_land @ delta_r
        horizontal_error = P_HORIZONTAL @ delta_r
        v_rel = V[:, k] - v_moon_k
        vertical_speed = n_land @ v_rel

        vmax_rel = 2.5 * (1.0 - frac)**1.3 + 0.030

        constraints += [
            cp.norm(v_rel, 2) <= vmax_rel + S_SPEED[j],
            altitude >= -S_ALT[j],
            cp.norm(horizontal_error, 2)
            <= np.tan(LANDING_CONE_ANGLE) * altitude + S_CONE[j],
            # Powered descent may hover, but it may never climb away from the
            # surface.  This removes the descend-rise-descend solution that an
            # altitude lower bound alone still permits.
            vertical_speed <= 0.0,
        ]

        if k < N:
            r_moon_next, _ = moon_state(TIME[k + 1])
            r_land_next = r_moon_next + R_M * n_land
            altitude_next = n_land @ (R[:, k + 1] - r_land_next)
            constraints += [altitude_next <= altitude]

        if frac >= 0.75:
            horizontal_speed = P_HORIZONTAL @ v_rel
            terminal_frac = (frac - 0.75) / 0.25
            max_down_speed = (
                0.080 * (1.0 - terminal_frac) + TOUCHDOWN_SPEED_MAX
            )
            max_horizontal = (
                0.050 * (1.0 - terminal_frac) + TOUCHDOWN_HORIZONTAL_MAX
            )

            constraints += [
                vertical_speed <= TOUCHDOWN_SPEED_MAX + S_TERMINAL[j],
                vertical_speed >= -max_down_speed - S_TERMINAL[j],
                cp.norm(horizontal_speed, 2)
                <= max_horizontal + S_TERMINAL[j],
                # Near the surface, allowable lateral speed collapses toward
                # the touchdown limit instead of permitting a long low hover
                # or sideways crawl.
                cp.norm(horizontal_speed, 2)
                <= (
                    TOUCHDOWN_HORIZONTAL_MAX
                    + LOW_ALT_HORIZONTAL_SPEED_SLOPE * altitude
                    + S_TERMINAL[j]
                ),
            ]

        if frac >= TERMINAL_CONE_START_FRACTION:
            constraints += [
                cp.norm(horizontal_error, 2)
                <= (
                    np.tan(TERMINAL_LANDING_CONE_ANGLE) * altitude
                    + S_CONE[j]
                )
            ]

    # -------------------------------------------------------------------------
    # Touchdown: soft during restoration, optionally exact during polishing.
    # -------------------------------------------------------------------------
    v_touch_rel = V[:, N] - v_moon_final

    if hard_landing:
        constraints += [
            R[:, N] == r_land_final,
            cp.norm(v_touch_rel, 2) <= TOUCHDOWN_SPEED_MAX,
            cp.norm(P_HORIZONTAL @ v_touch_rel, 2)
            <= TOUCHDOWN_HORIZONTAL_MAX,
            n_land @ v_touch_rel <= 0.0,
            cp.norm(v_touch_rel - v_touch_target, 2)
            <= TOUCHDOWN_TARGET_TOL,
            S_CONE == 0,
            S_SPEED == 0,
            S_ALT == 0,
            S_TERMINAL == 0,
            S_TOUCH_POS == 0,
            S_TOUCH_SPEED == 0,
            S_TOUCH_HORIZ == 0,
        ]
    else:
        constraints += [
            cp.norm(R[:, N] - r_land_final, 2) <= 0.050 + S_TOUCH_POS,
            cp.norm(v_touch_rel, 2)
            <= TOUCHDOWN_SPEED_MAX + S_TOUCH_SPEED,
            cp.norm(P_HORIZONTAL @ v_touch_rel, 2)
            <= TOUCHDOWN_HORIZONTAL_MAX + S_TOUCH_HORIZ,
            n_land @ v_touch_rel <= S_TOUCH_SPEED,
            cp.norm(v_touch_rel - v_touch_target, 2)
            <= TOUCHDOWN_TARGET_TOL + S_TOUCH_SPEED,
        ]

    # -------------------------------------------------------------------------
    # Objective.
    # -------------------------------------------------------------------------
    # Dimensionally normalized feasibility score.
    landing_slack_cost = (
        cp.sum(S_CONE) / 10.0
        + cp.sum(S_ALT) / 10.0
        + cp.sum(S_SPEED) / 0.05
        + cp.sum(S_TERMINAL) / 0.02
        + S_TOUCH_POS / 0.05
        + S_TOUCH_SPEED / 0.002
        + S_TOUCH_HORIZ / 0.0015
    )

    tracking_cost = cp.sum_squares((R - r_ref) / D_EM)

    if mode == "feasibility":
        objective = cp.Minimize(
            5.0e4 * virtual_dv_cost
            + 2.0e3 * landing_slack_cost
            + 1.0e-4 * thrust_smooth_cost
            + 1.0e-2 * tracking_cost
            + 1.0e-5 * propellant_cost_kg
        )
    else:
        objective = cp.Minimize(
            propellant_cost_kg / 1000.0
            + 1.0e5 * virtual_dv_cost
            + 5.0e3 * landing_slack_cost
            + 1.0e-4 * thrust_smooth_cost
            + 1.0e-2 * tracking_cost
        )

    problem = cp.Problem(objective, constraints)

    variables = dict(
        R=R,
        V=V,
        THRUST=THRUST,
        MASS=MASS,
        SIGMA=SIGMA,
        NU=NU,
        S_CONE=S_CONE,
        S_SPEED=S_SPEED,
        S_ALT=S_ALT,
        S_TERMINAL=S_TERMINAL,
        S_TOUCH_POS=S_TOUCH_POS,
        S_TOUCH_SPEED=S_TOUCH_SPEED,
        S_TOUCH_HORIZ=S_TOUCH_HORIZ,
        propellant_cost_kg=propellant_cost_kg,
    )

    return problem, variables


def read_slack_metrics(var):
    return {
        "cone_km": float(np.max(np.asarray(var["S_CONE"].value))),
        "speed_mps": float(np.max(np.asarray(var["S_SPEED"].value))) * 1000.0,
        "alt_km": float(np.max(np.asarray(var["S_ALT"].value))),
        "terminal_mps": float(np.max(np.asarray(var["S_TERMINAL"].value))) * 1000.0,
        "touch_pos_m": float(var["S_TOUCH_POS"].value) * 1000.0,
        "touch_speed_mps": float(var["S_TOUCH_SPEED"].value) * 1000.0,
        "touch_horiz_mps": float(var["S_TOUCH_HORIZ"].value) * 1000.0,
    }


def solve_one_scp_iteration(iteration, mode, hard_landing=False):
    """Retry automatically with a larger trust region if needed."""
    retry_scales = [1.0, 2.5, 6.0]

    for retry, trust_multiplier in enumerate(retry_scales, start=1):
        problem, var = build_scp_problem(
            mode=mode,
            iteration=iteration,
            trust_multiplier=trust_multiplier,
            hard_landing=hard_landing,
        )

        print(
            f"  attempt {retry}: mode={mode}, hard={hard_landing}, "
            f"trust x{trust_multiplier:.1f}"
        )
        print("  DCP:", problem.is_dcp())
        if not problem.is_dcp():
            raise RuntimeError("Convex SCP subproblem is not DCP-compliant.")

        try:
            solver_used = solve_with_available_solver(problem)
        except cp.error.SolverError:
            solver_used = "solver error"

        print("  Solver:", solver_used)
        print("  Status:", problem.status)
        print("  Objective:", problem.value)

        if problem.status in (cp.OPTIMAL, cp.OPTIMAL_INACCURATE):
            return problem, var

    return None, None


# Diagnostic for the improved initial reference.
ref_cone_violations = []
for k in range(K_DESCENT_START, N + 1):
    r_moon_k, _ = moon_state(TIME[k])
    r_land_k = r_moon_k + R_M * n_land
    d = r_ref[:, k] - r_land_k
    h = n_land @ d
    lateral = np.linalg.norm(P_HORIZONTAL @ d)
    ref_cone_violations.append(
        max(0.0, lateral - np.tan(LANDING_CONE_ANGLE) * h)
    )

print("\n================ INITIAL REFERENCE CHECK ================")
print(f"Max landing-cone violation: {max(ref_cone_violations):.6f} km")
print(
    "Reference touchdown Moon-relative speed: "
    f"{np.linalg.norm(v_ref[:, N] - v_moon_final) * 1000.0:.6f} m/s"
)
print(f"Reference descent-start mass: {mass_ref[K_DESCENT_START]:.2f} kg")
print(f"Reference final mass:         {mass_ref[-1]:.2f} kg")


for iteration in range(MAX_SCP_ITER):
    mode = "feasibility" if iteration < FEASIBILITY_ITERS else "fuel"
    print(
        f"\n================ SCP iteration {iteration + 1}/{MAX_SCP_ITER} "
        f"({mode}) ================"
    )

    problem, var = solve_one_scp_iteration(
        iteration=iteration,
        mode=mode,
        hard_landing=False,
    )

    if problem is None:
        raise RuntimeError(
            "Even the soft feasibility subproblem is infeasible after trust-region retries. "
            "Inspect TLI/LEO bounds or increase the retry trust scales."
        )

    r_new = np.asarray(var["R"].value)
    v_new = np.asarray(var["V"].value)
    t_new = np.asarray(var["THRUST"].value)
    m_new = np.asarray(var["MASS"].value)
    sigma_new = np.asarray(var["SIGMA"].value)
    nu_new = np.asarray(var["NU"].value)

    virtual_dv = np.sum(np.linalg.norm(nu_new, axis=0) * DT)
    rms_r_change = np.sqrt(np.mean(np.sum((r_new - r_ref)**2, axis=0)))
    rms_m_change = np.sqrt(np.mean((m_new - mass_ref)**2))
    propellant_now = float(var["propellant_cost_kg"].value)
    slack_metrics = read_slack_metrics(var)

    print(f"Propellant used:     {propellant_now:10.2f} kg")
    print(f"Final mass:          {m_new[-1]:10.2f} kg")
    print(f"Virtual delta-v:     {virtual_dv:10.6f} km/s")
    print(f"RMS trajectory move: {rms_r_change:10.3f} km")
    print(f"RMS mass move:       {rms_m_change:10.3f} kg")
    print("Landing slack metrics:")
    for key, value in slack_metrics.items():
        print(f"  {key:18s}: {value:.6f}")

    R_solution = r_new
    V_solution = v_new
    T_solution = t_new
    M_solution = m_new
    SIGMA_solution = sigma_new
    NU_solution = nu_new
    LAST_SLACKS = slack_metrics

    # Damped reference update.
    alpha = REFERENCE_UPDATE_ALPHA if mode == "feasibility" else 0.65
    r_ref = alpha * r_new + (1.0 - alpha) * r_ref
    v_ref = alpha * v_new + (1.0 - alpha) * v_ref
    thrust_ref = alpha * t_new + (1.0 - alpha) * thrust_ref
    mass_ref = alpha * m_new + (1.0 - alpha) * mass_ref

    landing_feasible = (
        slack_metrics["cone_km"] < 1.0e-3
        and slack_metrics["speed_mps"] < 0.05
        and slack_metrics["alt_km"] < 1.0e-3
        and slack_metrics["terminal_mps"] < 0.05
        and slack_metrics["touch_pos_m"] < 0.5
        and slack_metrics["touch_speed_mps"] < 0.02
        and slack_metrics["touch_horiz_mps"] < 0.02
    )

    if (
        mode == "fuel"
        and landing_feasible
        and virtual_dv < VIRTUAL_DV_TOL
        and rms_r_change < TRAJECTORY_CHANGE_TOL
        and rms_m_change < MASS_CHANGE_TOL
    ):
        print("Soft SCP converged with essentially zero landing slack.")
        break


# -----------------------------------------------------------------------------
# Optional exact hard-constraint polishing solve.
# -----------------------------------------------------------------------------
if R_solution is not None and LAST_SLACKS is not None:
    near_hard_feasible = (
        LAST_SLACKS["cone_km"] < 0.05
        and LAST_SLACKS["speed_mps"] < 2.0
        and LAST_SLACKS["touch_pos_m"] < 100.0
        and LAST_SLACKS["touch_speed_mps"] < 2.0
    )

    if near_hard_feasible:
        print("\n================ HARD LANDING POLISH ================")
        problem_hard, var_hard = solve_one_scp_iteration(
            iteration=MAX_SCP_ITER,
            mode="fuel",
            hard_landing=True,
        )

        if problem_hard is not None:
            R_solution = np.asarray(var_hard["R"].value)
            V_solution = np.asarray(var_hard["V"].value)
            T_solution = np.asarray(var_hard["THRUST"].value)
            M_solution = np.asarray(var_hard["MASS"].value)
            SIGMA_solution = np.asarray(var_hard["SIGMA"].value)
            NU_solution = np.asarray(var_hard["NU"].value)
            print("Hard landing polish succeeded.")
        else:
            print("Hard polish was infeasible; keeping the best soft-feasible solution.")
    else:
        print(
            "\nHard landing polish skipped because the soft solution still has "
            "non-negligible landing slack."
        )

# =============================================================================
# 13. POST-PROCESS / NONLINEAR CONSISTENCY CHECK
# =============================================================================

if R_solution is None:
    raise RuntimeError("No solution was produced.")

THRUST_MAG = np.linalg.norm(T_solution, axis=0)
PROPER_ACCEL = THRUST_MAG / M_solution[:-1]          # km/s^2
PROPER_ACCEL_G = PROPER_ACCEL / G0
PROP_FUEL_USED = float(np.sum([
    DT[k] * SIGMA_solution[k] / (phase_isp(k) * G0)
    for k in range(N)
]))
TOTAL_MASS_LOSS = MASS_INITIAL - M_solution[-1]

# Moon history.
moon_positions = np.zeros((3, N + 1))
moon_velocities = np.zeros((3, N + 1))
for k in range(N + 1):
    moon_positions[:, k], moon_velocities[:, k] = moon_state(TIME[k])

moon_rel_pos = R_solution - moon_positions
moon_rel_vel = V_solution - moon_velocities
moon_rel_speed = np.linalg.norm(moon_rel_vel, axis=0)

descent_altitude = np.array([
    n_land @ (
        R_solution[:, k]
        - (moon_positions[:, k] + R_M * n_land)
    )
    for k in range(K_DESCENT_START, N + 1)
])
descent_altitude_change = np.diff(descent_altitude)
max_descent_climb = max(float(np.max(descent_altitude_change)), 0.0)

# Check exact nonlinear one-step defect using solved T/M and exact gravity.
pos_defects = []
vel_defects = []
for k in range(N):
    dt = DT[k]
    a_exact = (
        gravity(R_solution[:, k], TIME[k])
        + T_solution[:, k] / M_solution[k]
    )

    r_pred = (
        R_solution[:, k]
        + dt * V_solution[:, k]
        + 0.5 * dt**2 * a_exact
    )
    v_pred = V_solution[:, k] + dt * a_exact

    pos_defects.append(np.linalg.norm(R_solution[:, k + 1] - r_pred))
    vel_defects.append(np.linalg.norm(V_solution[:, k + 1] - v_pred))

pos_defects = np.asarray(pos_defects)
vel_defects = np.asarray(vel_defects)

print("\n================ FINAL RESULT ================")
print(f"Mission duration:               {T_TOTAL / 3600.0:.2f} h")
print(f"Initial mass:                   {MASS_INITIAL:.2f} kg")
print(f"Final mass:                     {M_solution[-1]:.2f} kg")
print(f"Propellant used:                {PROP_FUEL_USED:.2f} kg")
print(f"Separated stage mass:           {STAGE_DROP_AT_DESCENT:.2f} kg")
print(f"Total vehicle mass loss:        {TOTAL_MASS_LOSS:.2f} kg")
print(f"Fuel remaining above dry mass:  {M_solution[-1] - MASS_DRY:.2f} kg")
print(f"Maximum thrust:                 {THRUST_MAG.max():.2f} kN")
print(f"Maximum proper acceleration:    {PROPER_ACCEL_G.max():.3f} g")
print(f"Max thrust-epigraph gap:         {np.max(SIGMA_solution - THRUST_MAG):.6f} kN")
print(
    "Touchdown Moon-relative speed:   "
    f"{moon_rel_speed[-1] * 1000.0:.3f} m/s"
)
print(f"Max exact nonlinear position defect: {pos_defects.max():.3f} km")
print(f"Max exact nonlinear velocity defect: {vel_defects.max():.6f} km/s")
print(f"Maximum altitude increase in descent: {max_descent_climb * 1000.0:.3f} m/step")
print(
    "Integrated virtual delta-v:       "
    f"{np.sum(np.linalg.norm(NU_solution, axis=0) * DT):.6f} km/s"
)


# =============================================================================
# 14. PLOTTING HELPERS
# =============================================================================


def sphere_mesh(center, radius, n=40):
    u = np.linspace(0.0, 2.0 * np.pi, n)
    v = np.linspace(0.0, np.pi, n)
    x = center[0] + radius * np.outer(np.cos(u), np.sin(v))
    y = center[1] + radius * np.outer(np.sin(u), np.sin(v))
    z = center[2] + radius * np.outer(np.ones_like(u), np.cos(v))
    return x, y, z


def set_equal_3d(ax, points):
    mins = points.min(axis=1)
    maxs = points.max(axis=1)
    mids = 0.5 * (mins + maxs)
    radius = 0.5 * np.max(maxs - mins)
    radius = max(radius, 1.0)
    ax.set_xlim(mids[0] - radius, mids[0] + radius)
    ax.set_ylim(mids[1] - radius, mids[1] + radius)
    ax.set_zlim(mids[2] - radius, mids[2] + radius)
    ax.set_box_aspect((1, 1, 1))


# =============================================================================
# 15. FULL 3-D EARTH -> MOON TRAJECTORY
# =============================================================================

fig = plt.figure(figsize=(12, 9))
ax = fig.add_subplot(111, projection="3d")

traj = R_solution / D_EM
moon_hist = moon_positions / D_EM

ax.plot(traj[0], traj[1], traj[2], linewidth=2.2, label="Spacecraft")
ax.plot(
    moon_hist[0], moon_hist[1], moon_hist[2],
    linestyle="--", linewidth=1.2, alpha=0.7, label="Moon path"
)

xe, ye, ze = sphere_mesh(np.zeros(3), R_E / D_EM)
ax.plot_surface(xe, ye, ze, alpha=0.7)

xm, ym, zm = sphere_mesh(r_moon_final / D_EM, R_M / D_EM)
ax.plot_surface(xm, ym, zm, alpha=0.8)

ax.scatter(*traj[:, 0], s=55, label="LEO start")
ax.scatter(*traj[:, K_TLI_START], s=65, marker="^", label="TLI start")
ax.scatter(*traj[:, K_TRANSFER_START], s=65, marker="o", label="TLI end")
ax.scatter(*traj[:, K_DESCENT_START], s=65, marker="s", label="Descent start")
ax.scatter(*traj[:, -1], s=100, marker="*", label="Touchdown")

ax.set_xlabel("X / Earth-Moon distance")
ax.set_ylabel("Y / Earth-Moon distance")
ax.set_zlabel("Z / Earth-Moon distance")
ax.set_title("3-D Earth -> Moon Landing with Continuous Thrust")
ax.legend()
ax.view_init(elev=28, azim=-55)
set_equal_3d(ax, np.hstack([traj, moon_hist]))
plt.tight_layout()


# =============================================================================
# 16. EARTH PARKING ORBIT + TLI ZOOM
# =============================================================================

fig = plt.figure(figsize=(9, 8))
ax = fig.add_subplot(111, projection="3d")

end = K_TRANSFER_START + 1
earth_seg = R_solution[:, :end]
ax.plot(
    earth_seg[0], earth_seg[1], earth_seg[2],
    linewidth=2.4, label="LEO + finite TLI"
)

xe, ye, ze = sphere_mesh(np.zeros(3), R_E)
ax.plot_surface(xe, ye, ze, alpha=0.50)

ax.scatter(
    *R_solution[:, K_TLI_START],
    s=80, marker="^", label="TLI ignition"
)
ax.scatter(
    *R_solution[:, K_TRANSFER_START],
    s=70, marker="o", label="TLI cutoff"
)

ax.set_xlabel("X [km]")
ax.set_ylabel("Y [km]")
ax.set_zlabel("Z [km]")
ax.set_title("Earth Parking Orbit and TLI")
ax.legend()
set_equal_3d(ax, earth_seg)
plt.tight_layout()


# =============================================================================
# 17. MOON-CENTERED DESCENT
# =============================================================================

fig = plt.figure(figsize=(9, 8))
ax = fig.add_subplot(111, projection="3d")

arrival = moon_rel_pos[:, K_DESCENT_START:]
ax.plot(
    arrival[0], arrival[1], arrival[2],
    linewidth=2.5, label="Powered descent"
)

xm, ym, zm = sphere_mesh(np.zeros(3), R_M)
ax.plot_surface(xm, ym, zm, alpha=0.50)

landing_relative = R_M * n_land
ax.scatter(*landing_relative, s=100, marker="*", label="Landing site")

ax.set_xlabel("Moon-relative X [km]")
ax.set_ylabel("Moon-relative Y [km]")
ax.set_zlabel("Moon-relative Z [km]")
ax.set_title("Moon-Centered Powered Descent")
ax.legend()
set_equal_3d(ax, arrival)
plt.tight_layout()


# =============================================================================
# 18. MASS / FUEL HISTORY
# =============================================================================

fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(TIME / 3600.0, M_solution, linewidth=2, label="Vehicle mass")
ax.axhline(MASS_DRY, linestyle="--", label="Dry-mass constraint")
ax.axvline(TIME[K_TLI_START] / 3600.0, linestyle="--", label="TLI start")
ax.axvline(TIME[K_DESCENT_START] / 3600.0, linestyle="--", label="Descent start")
ax.set_xlabel("Mission time [h]")
ax.set_ylabel("Mass [kg]")
ax.set_title("Mass / Fuel Consumption")
ax.grid(True)
ax.legend()
plt.tight_layout()


# =============================================================================
# 19. THRUST HISTORY
# =============================================================================

fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(TIME[:-1] / 3600.0, THRUST_MAG, linewidth=2, label="Thrust magnitude")
ax.axhline(TMAX_DESCENT, linestyle=":", label="Descent Tmax")
ax.axvline(TIME[K_TLI_START] / 3600.0, linestyle="--", label="TLI start")
ax.axvline(TIME[K_TRANSFER_START] / 3600.0, linestyle="--", label="TLI cutoff")
ax.axvline(TIME[K_DESCENT_START] / 3600.0, linestyle="--", label="Descent start")
ax.set_xlabel("Mission time [h]")
ax.set_ylabel("Thrust [kN]")
ax.set_title("Optimized Continuous Thrust")
ax.grid(True)
ax.legend()
plt.tight_layout()


# =============================================================================
# 20. ACCELERATION HISTORY
# =============================================================================

fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(TIME[:-1] / 3600.0, PROPER_ACCEL_G, linewidth=2)
ax.set_xlabel("Mission time [h]")
ax.set_ylabel("Proper acceleration [g]")
ax.set_title("Propulsive Acceleration")
ax.grid(True)
plt.tight_layout()


# =============================================================================
# 21. SPEED HISTORY
# =============================================================================

fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(
    TIME / 3600.0,
    np.linalg.norm(V_solution, axis=0),
    label="Earth-inertial speed",
)
ax.plot(
    TIME / 3600.0,
    moon_rel_speed,
    label="Moon-relative speed",
)
ax.axvline(TIME[K_TLI_START] / 3600.0, linestyle="--", label="TLI")
ax.axvline(TIME[K_DESCENT_START] / 3600.0, linestyle="--", label="Descent")
ax.set_xlabel("Mission time [h]")
ax.set_ylabel("Speed [km/s]")
ax.set_title("Spacecraft Speed")
ax.grid(True)
ax.legend()
plt.tight_layout()


# =============================================================================
# 22. LEO ALTITUDE HISTORY
# =============================================================================

leo_altitude = np.linalg.norm(R_solution[:, :N_PARK + 1], axis=0) - R_E
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.plot(TIME[:N_PARK + 1] / 60.0, leo_altitude, linewidth=2)
ax.axhline(LEO_ALT_MIN, linestyle="--", label="LEO min")
ax.axhline(LEO_ALT_MAX, linestyle="--", label="LEO max")
ax.set_xlabel("Mission time [min]")
ax.set_ylabel("Earth altitude [km]")
ax.set_title("Earth Parking-Orbit Environment")
ax.grid(True)
ax.legend()
plt.tight_layout()

plt.close("all")


# =============================================================================
# 23. MATPLOTLIB-ONLY 3-D ANIMATION EXPORT
# =============================================================================

# Plotly is intentionally NOT used in this file.
# Static PNG is the default output. Legacy MP4 helpers remain optional.
#
# Improvements in this visualization section:
#   1) cylindrical rocket + nose cone
#   2) thrust-force arrow (+T direction)
#   3) exhaust flame cone (-T direction), length proportional to thrust
#   4) Moon-centered approach animation
#   5) landing-site local ENU animation with adaptive camera zoom
#   6) live altitude / speed / thrust / mass / propellant telemetry

GENERATE_MPL_MP4 = False
GENERATE_COMBINED_MISSION = False
GENERATE_STATIC_SUMMARY = True
SHOW_ANIMATION_WINDOW = False

ANIMATION_FPS = 100
OVERVIEW_FRAMES = 400
DESCENT_FRAMES = 450
LANDING_FRAMES = 550
GROUND_VIEW_START_ALT_KM = 25.0

OVERVIEW_MP4 = "./apollo_mission_overview_matplotlib_100fps.mp4"
DESCENT_MP4 = "./apollo_descent_moon_context_matplotlib_100fps.mp4"
LANDING_MP4 = "./apollo_landing_ground_view_matplotlib_100fps.mp4"
COMBINED_MP4 = "./apollo_mission_complete_matplotlib_100fps.mp4"
STATIC_SUMMARY_PNG = "./apollo_mission_2d_summary.png"

def interp_rows(data, t_old, t_new):
    """Interpolate 1-D or row-wise 2-D data onto a new time grid."""
    data = np.asarray(data)
    if data.ndim == 1:
        return np.interp(t_new, t_old, data)
    return np.vstack([
        np.interp(t_new, t_old, data[i])
        for i in range(data.shape[0])
    ])


def unit_vector(v, fallback=None):
    v = np.asarray(v, dtype=float)
    n = np.linalg.norm(v)
    if n > 1.0e-12:
        return v / n

    if fallback is not None:
        fallback = np.asarray(fallback, dtype=float)
        nf = np.linalg.norm(fallback)
        if nf > 1.0e-12:
            return fallback / nf

    return np.array([0.0, 0.0, 1.0])


def body_basis(axis):
    """Return two orthonormal vectors perpendicular to axis."""
    axis = unit_vector(axis)
    helper = np.array([0.0, 0.0, 1.0])
    if abs(np.dot(axis, helper)) > 0.95:
        helper = np.array([0.0, 1.0, 0.0])

    e1 = unit_vector(np.cross(axis, helper))
    e2 = unit_vector(np.cross(axis, e1))
    return e1, e2


def cylinder_mesh(center, axis, length, radius, n_theta=16):
    """Create a cylindrical rocket body aligned with axis."""
    axis = unit_vector(axis)
    e1, e2 = body_basis(axis)

    theta = np.linspace(0.0, 2.0 * np.pi, n_theta)
    axial = np.array([-0.5 * length, 0.5 * length])

    X = np.zeros((2, n_theta))
    Y = np.zeros((2, n_theta))
    Z = np.zeros((2, n_theta))

    for j, s in enumerate(axial):
        ring_center = center + s * axis
        for i, th in enumerate(theta):
            p = (
                ring_center
                + radius * np.cos(th) * e1
                + radius * np.sin(th) * e2
            )
            X[j, i], Y[j, i], Z[j, i] = p

    return X, Y, Z


def cone_mesh(tip, axis, length, radius, n_theta=16):
    """Create a cone whose pointed tip is 'tip' and axis points toward the tip."""
    axis = unit_vector(axis)
    e1, e2 = body_basis(axis)

    theta = np.linspace(0.0, 2.0 * np.pi, n_theta)
    X = np.zeros((2, n_theta))
    Y = np.zeros((2, n_theta))
    Z = np.zeros((2, n_theta))

    base_center = tip - length * axis
    for i, th in enumerate(theta):
        p = (
            base_center
            + radius * np.cos(th) * e1
            + radius * np.sin(th) * e2
        )
        X[0, i], Y[0, i], Z[0, i] = p
        X[1, i], Y[1, i], Z[1, i] = tip

    return X, Y, Z


def flame_mesh(nozzle, exhaust_direction, length, radius, n_theta=14):
    """Cone with wide base at nozzle and pointed tip downstream."""
    exhaust_direction = unit_vector(exhaust_direction)
    e1, e2 = body_basis(exhaust_direction)
    theta = np.linspace(0.0, 2.0 * np.pi, n_theta)
    tip = nozzle + length * exhaust_direction

    X = np.zeros((2, n_theta))
    Y = np.zeros((2, n_theta))
    Z = np.zeros((2, n_theta))

    for i, th in enumerate(theta):
        base = (
            nozzle
            + radius * np.cos(th) * e1
            + radius * np.sin(th) * e2
        )
        X[0, i], Y[0, i], Z[0, i] = base
        X[1, i], Y[1, i], Z[1, i] = tip

    return X, Y, Z


def rocket_mesh(position, direction, total_length, body_radius):
    """Return body/nose mesh plus rear nozzle position."""
    direction = unit_vector(direction)

    body_length = 0.76 * total_length
    nose_length = 0.24 * total_length

    body_center = position - 0.12 * total_length * direction
    nose_tip = position + 0.50 * total_length * direction
    nozzle = position - 0.50 * total_length * direction

    body = cylinder_mesh(
        body_center,
        direction,
        body_length,
        body_radius,
    )
    nose = cone_mesh(
        nose_tip,
        direction,
        nose_length,
        body_radius,
    )
    return body, nose, nozzle


def sphere_mesh(center, radius, n_u=22, n_v=12):
    u = np.linspace(0.0, 2.0 * np.pi, n_u)
    v = np.linspace(0.0, np.pi, n_v)
    X = center[0] + radius * np.outer(np.cos(u), np.sin(v))
    Y = center[1] + radius * np.outer(np.sin(u), np.sin(v))
    Z = center[2] + radius * np.outer(np.ones_like(u), np.cos(v))
    return X, Y, Z


def lunar_surface_patch(half_width, n=45):
    """Flat landing-site tangent plane used as the local lunar ground."""
    x = np.linspace(-half_width, half_width, n)
    y = np.linspace(-half_width, half_width, n)
    X, Y = np.meshgrid(x, y)
    Z = np.zeros_like(X)
    return X, Y, Z


def set_3d_bounds(ax, points, padding_fraction=0.10):
    points = np.asarray(points)
    mins = points.min(axis=1)
    maxs = points.max(axis=1)
    span = np.max(maxs - mins)
    pad = max(span * padding_fraction, 1.0)

    ax.set_xlim(mins[0] - pad, maxs[0] + pad)
    ax.set_ylim(mins[1] - pad, maxs[1] + pad)
    ax.set_zlim(mins[2] - pad, maxs[2] + pad)
    ax.set_box_aspect((
        maxs[0] - mins[0] + 2 * pad,
        maxs[1] - mins[1] + 2 * pad,
        maxs[2] - mins[2] + 2 * pad,
    ))


def phase_name(t):
    if t < TIME[K_TLI_START]:
        return "Earth parking orbit"
    if t < TIME[K_TRANSFER_START]:
        return "TLI burn"
    if t < TIME[K_DESCENT_START]:
        return "Translunar transfer / MCC"
    return "Lunar powered descent"


def phase_tmax(t):
    if t < TIME[K_TLI_START]:
        return 1.0
    if t < TIME[K_TRANSFER_START]:
        return TMAX_TLI
    if t < TIME[K_DESCENT_START]:
        return TMAX_MCC
    return TMAX_DESCENT


def thrust_fraction(thrust_vector, t):
    return float(np.clip(
        np.linalg.norm(thrust_vector) / max(phase_tmax(t), 1.0e-9),
        0.0,
        1.0,
    ))


def add_thrust_visuals(
    ax,
    position,
    thrust_vector,
    body_axis,
    rocket_length,
    rocket_radius,
    t,
    artist_list,
    arrow_scale=1.4,
    flame_scale=1.7,
    min_arrow_fraction=0.18,
):
    """Add +T force arrow and -T exhaust flame. Artists are removable next frame."""
    thrust_mag = np.linalg.norm(thrust_vector)
    if thrust_mag < 1.0e-6:
        return

    t_dir = unit_vector(thrust_vector, fallback=body_axis)
    frac = thrust_fraction(thrust_vector, t)

    # +T force arrow from vehicle center.
    # Keep low-thrust navigation corrections legible.  Magnitude still changes
    # the arrow length, but the display does not collapse to a nearly invisible
    # mark at the Earth-Moon overview scale.
    display_frac = min_arrow_fraction + (1.0 - min_arrow_fraction) * frac
    arrow_length = rocket_length * arrow_scale * display_frac
    q = ax.quiver(
        position[0], position[1], position[2],
        t_dir[0], t_dir[1], t_dir[2],
        length=arrow_length,
        normalize=True,
        color="tab:red",
        linewidth=3.2,
        arrow_length_ratio=0.26,
    )
    artist_list.append(q)

    # Exhaust leaves the nozzle opposite to thrust direction.
    nozzle = position - 0.50 * rocket_length * unit_vector(body_axis)
    flame_length = rocket_length * flame_scale * frac
    flame_radius = rocket_radius * (0.55 + 0.45 * frac)

    if flame_length > 1.0e-5:
        Xf, Yf, Zf = flame_mesh(
            nozzle,
            -t_dir,
            flame_length,
            flame_radius,
        )
        flame = ax.plot_surface(
            Xf, Yf, Zf,
            alpha=0.72,
            linewidth=0,
            antialiased=False,
        )
        artist_list.append(flame)


def cumulative_propellant_nodes():
    prop = np.zeros(N + 1)
    for k in range(N):
        prop[k + 1] = prop[k] + (
            DT[k] * SIGMA_solution[k]
            / (phase_isp(k) * G0)
        )
    return prop


PROP_CUM_NODES = cumulative_propellant_nodes()


def write_animation_mp4(anim, output_path, fps):
    """Write MP4 only when ffmpeg is available."""
    if shutil.which("ffmpeg") is None:
        print("ffmpeg not found -> MP4 export skipped:", output_path)
        return

    writer = FFMpegWriter(
        fps=fps,
        metadata={"artist": "Matplotlib"},
        bitrate=6000,
    )
    anim.save(output_path, writer=writer, dpi=120)
    print(f"Wrote Matplotlib MP4 animation: {output_path}")


# =============================================================================
# 24. FULL EARTH -> MOON MATPLOTLIB ANIMATION
# =============================================================================


def create_overview_animation():
    animation_time = np.linspace(0.0, T_TOTAL, OVERVIEW_FRAMES)
    R_anim = interp_rows(R_solution, TIME, animation_time)
    V_anim = interp_rows(V_solution, TIME, animation_time)
    T_anim = interp_rows(T_solution, TIME[:-1], animation_time)
    moon_anim = interp_rows(moon_positions, TIME, animation_time)
    thrust_mag_anim = np.linalg.norm(T_anim, axis=0)
    thrust_frac_anim = np.array([
        thrust_fraction(T_anim[:, i], animation_time[i])
        for i in range(len(animation_time))
    ])

    # Physically scaled rocket is invisible at Earth-Moon scale.
    rocket_length = 0.026 * D_EM
    rocket_radius = 0.0050 * D_EM

    fig = plt.figure(figsize=(11.5, 8.5))
    ax = fig.add_subplot(111, projection="3d")

    ax.plot(
        R_solution[0], R_solution[1], R_solution[2],
        linewidth=1.7, alpha=0.32, label="Optimized trajectory",
    )
    ax.plot(
        moon_positions[0], moon_positions[1], moon_positions[2],
        linestyle="--", linewidth=1.0, alpha=0.35, label="Moon path",
    )

    earth_X, earth_Y, earth_Z = sphere_mesh(np.zeros(3), R_E)
    ax.plot_surface(
        earth_X, earth_Y, earth_Z,
        alpha=0.65, linewidth=0, antialiased=True,
    )

    progress_line, = ax.plot([], [], [], linewidth=3.4, label="Mission progress")
    spacecraft_point, = ax.plot(
        [], [], [], marker="o", markersize=7, linestyle="None",
        markeredgecolor="white", markeredgewidth=1.0,
    )
    moon_point, = ax.plot([], [], [], marker="o", markersize=10, linestyle="None", label="Moon")
    landing_marker, = ax.plot(
        [r_land_final[0]], [r_land_final[1]], [r_land_final[2]],
        marker="*", markersize=13, linestyle="None", label="Landing site"
    )

    scene_points = np.hstack([R_solution, moon_positions, np.zeros((3, 1))])
    set_3d_bounds(ax, scene_points, padding_fraction=0.025)

    ax.set_xlabel("X [km]")
    ax.set_ylabel("Y [km]")
    ax.set_zlabel("Z [km]")
    ax.view_init(elev=27, azim=-54)
    ax.legend(loc="upper left")

    # Mission-wide thrust program.  Normalizing by each phase's engine limit
    # keeps small MCC/descent commands visible beside the much larger TLI burn.
    thrust_ax = fig.add_axes([0.64, 0.69, 0.30, 0.16])
    thrust_ax.plot(
        animation_time / 3600.0,
        100.0 * thrust_frac_anim,
        color="tab:red",
        linewidth=1.5,
    )
    thrust_ax.fill_between(
        animation_time / 3600.0,
        0.0,
        100.0 * thrust_frac_anim,
        color="tab:red",
        alpha=0.18,
    )
    thrust_cursor = thrust_ax.axvline(0.0, color="black", linewidth=1.2)
    thrust_dot, = thrust_ax.plot([], [], marker="o", color="tab:red", markersize=5)
    thrust_ax.set_xlim(0.0, T_TOTAL / 3600.0)
    thrust_ax.set_ylim(0.0, 105.0)
    thrust_ax.set_xlabel("Mission time [h]", fontsize=8)
    thrust_ax.set_ylabel("Phase max [%]", fontsize=8)
    thrust_ax.set_title("Thrust program (phase-normalized)", fontsize=9)
    thrust_ax.tick_params(labelsize=7)
    thrust_ax.grid(alpha=0.22)

    thrust_hud = ax.text2D(
        0.02, 0.02, "",
        transform=ax.transAxes,
        va="bottom",
        family="monospace",
    )

    dynamic_artists = []

    def clear_dynamic():
        while dynamic_artists:
            artist = dynamic_artists.pop()
            try:
                artist.remove()
            except (ValueError, AttributeError):
                pass

    def update(frame_idx):
        clear_dynamic()

        ti = animation_time[frame_idx]
        p = R_anim[:, frame_idx]
        thrust_vec = T_anim[:, frame_idx]
        axis = unit_vector(thrust_vec, fallback=V_anim[:, frame_idx])

        body, nose, _ = rocket_mesh(p, axis, rocket_length, rocket_radius)
        Xb, Yb, Zb = body
        Xn, Yn, Zn = nose

        body_artist = ax.plot_surface(
            Xb, Yb, Zb, alpha=0.95, linewidth=0, antialiased=False,
        )
        nose_artist = ax.plot_surface(
            Xn, Yn, Zn, alpha=0.98, linewidth=0, antialiased=False,
        )
        dynamic_artists.extend([body_artist, nose_artist])

        add_thrust_visuals(
            ax,
            p,
            thrust_vec,
            axis,
            rocket_length,
            rocket_radius,
            ti,
            dynamic_artists,
            arrow_scale=2.6,
            flame_scale=1.3,
            min_arrow_fraction=0.32,
        )

        progress_line.set_data(R_anim[0, :frame_idx + 1], R_anim[1, :frame_idx + 1])
        progress_line.set_3d_properties(R_anim[2, :frame_idx + 1])
        spacecraft_point.set_data([p[0]], [p[1]])
        spacecraft_point.set_3d_properties([p[2]])

        mp = moon_anim[:, frame_idx]
        moon_point.set_data([mp[0]], [mp[1]])
        moon_point.set_3d_properties([mp[2]])

        thrust_kn = thrust_mag_anim[frame_idx]
        engine_limit_kn = phase_tmax(ti)
        thrust_percent = 100.0 * thrust_frac_anim[frame_idx]
        thrust_cursor.set_xdata([ti / 3600.0, ti / 3600.0])
        thrust_dot.set_data([ti / 3600.0], [thrust_percent])
        thrust_hud.set_text(
            "THRUST COMMAND\n"
            f"phase  {phase_name(ti)}\n"
            f"T      {thrust_kn:8.2f} / {engine_limit_kn:.1f} kN\n"
            f"power  {thrust_percent:8.1f} %\n"
            f"Tx     {thrust_vec[0]:8.2f} kN\n"
            f"Ty     {thrust_vec[1]:8.2f} kN\n"
            f"Tz     {thrust_vec[2]:8.2f} kN\n"
            "red arrow = commanded direction"
        )
        ax.set_title(
            "Earth -> Moon trajectory | "
            f"t={ti / 3600.0:.2f} h | {phase_name(ti)} | "
            f"thrust={thrust_kn:.1f} kN\n"
            "Arrow = thrust force, flame = exhaust; rocket scale exaggerated"
        )

        return [
            progress_line,
            spacecraft_point,
            moon_point,
            landing_marker,
            thrust_cursor,
            thrust_dot,
            thrust_hud,
            *dynamic_artists,
        ]

    anim = FuncAnimation(
        fig,
        update,
        frames=len(animation_time),
        interval=1000.0 / ANIMATION_FPS,
        blit=False,
        repeat=False,
    )
    return fig, anim


# =============================================================================
# 25. MOON-CENTERED DESCENT — LANDING-SITE TRACKING CAMERA
# =============================================================================


def create_descent_context_animation():
    t_start = TIME[K_DESCENT_START]
    animation_time = np.linspace(t_start, T_TOTAL, DESCENT_FRAMES)

    R_abs = interp_rows(R_solution, TIME, animation_time)
    V_abs = interp_rows(V_solution, TIME, animation_time)
    T_anim = interp_rows(T_solution, TIME[:-1], animation_time)
    moon_anim = interp_rows(moon_positions, TIME, animation_time)
    M_anim = interp_rows(M_solution, TIME, animation_time)
    prop_anim = np.interp(animation_time, TIME, PROP_CUM_NODES)

    moon_vel = np.vstack([moon_state(t)[1] for t in animation_time]).T
    R_rel = R_abs - moon_anim
    landing_rel = R_M * n_land

    rocket_length = 70.0  # km, visualization only
    rocket_radius = 12.0  # km, visualization only

    fig = plt.figure(figsize=(11.5, 8.5))
    ax = fig.add_subplot(111, projection="3d")

    moon_X, moon_Y, moon_Z = sphere_mesh(np.zeros(3), R_M, n_u=26, n_v=14)
    ax.plot_surface(
        moon_X, moon_Y, moon_Z,
        alpha=0.62, linewidth=0, antialiased=True,
    )

    ax.plot(
        R_rel[0], R_rel[1], R_rel[2],
        linewidth=1.0, alpha=0.20, label="Optimized descent path",
    )

    progress_line, = ax.plot([], [], [], linewidth=2.8, label="Descent progress")
    spacecraft_point, = ax.plot([], [], [], marker="o", markersize=4, linestyle="None")
    landing_marker, = ax.plot(
        [landing_rel[0]], [landing_rel[1]], [landing_rel[2]],
        marker="*", markersize=12, linestyle="None", label="Landing site"
    )

    # Look across the descent plane instead of from an arbitrary global angle.
    # This makes altitude and down-range motion visually distinct while keeping
    # the lunar limb behind the vehicle.  The direction stays fixed, avoiding
    # a distracting camera orbit during the descent.
    initial_offset = R_rel[:, 0] - landing_rel
    approach_tangent = initial_offset - np.dot(initial_offset, n_land) * n_land
    if np.linalg.norm(approach_tangent) < 1.0e-9:
        v_rel_initial = V_abs[:, 0] - moon_vel[:, 0]
        approach_tangent = v_rel_initial - np.dot(v_rel_initial, n_land) * n_land
    view_direction = unit_vector(
        np.cross(n_land, approach_tangent),
        fallback=np.array([1.0, 0.0, 0.0]),
    )
    camera_elev = np.degrees(np.arcsin(np.clip(view_direction[2], -1.0, 1.0)))
    camera_azim = np.degrees(np.arctan2(view_direction[1], view_direction[0]))

    initial_distance = float(np.linalg.norm(initial_offset))
    initial_view_radius = max(0.68 * initial_distance, 120.0)
    initial_center = landing_rel + 0.45 * initial_offset
    ax.set_xlim(initial_center[0] - initial_view_radius, initial_center[0] + initial_view_radius)
    ax.set_ylim(initial_center[1] - initial_view_radius, initial_center[1] + initial_view_radius)
    ax.set_zlim(initial_center[2] - initial_view_radius, initial_center[2] + initial_view_radius)
    ax.set_box_aspect((1.0, 1.0, 1.0))

    ax.set_xlabel("Moon-relative X [km]")
    ax.set_ylabel("Moon-relative Y [km]")
    ax.set_zlabel("Moon-relative Z [km]")

    ax.view_init(elev=camera_elev, azim=camera_azim)
    ax.set_proj_type("persp", focal_length=1.15)
    ax.legend(loc="upper left")

    tracking_view_note = ax.text2D(
        0.69, 0.02,
        "DESCENT-PLANE SIDE VIEW\nLANDING-SITE TRACKING\nSMOOTH APPROACH ZOOM",
        transform=ax.transAxes,
        va="bottom",
        ha="left",
        family="monospace",
    )

    dynamic_artists = []

    def clear_dynamic():
        while dynamic_artists:
            artist = dynamic_artists.pop()
            try:
                artist.remove()
            except (ValueError, AttributeError):
                pass

    def update(frame_idx):
        clear_dynamic()

        ti = animation_time[frame_idx]
        p = R_rel[:, frame_idx]
        v_rel = V_abs[:, frame_idx] - moon_vel[:, frame_idx]
        thrust_vec = T_anim[:, frame_idx]
        axis = unit_vector(thrust_vec, fallback=v_rel)

        # Follow the midpoint between the vehicle and landing site.  The view
        # tightens continuously, but retains enough lunar surface to preserve
        # scale and direction near touchdown.
        remaining = p - landing_rel
        remaining_distance = float(np.linalg.norm(remaining))
        zoom_fraction = np.clip(remaining_distance / max(initial_distance, 1.0), 0.0, 1.0)
        smooth_zoom = zoom_fraction * zoom_fraction * (3.0 - 2.0 * zoom_fraction)
        view_radius = 85.0 + (initial_view_radius - 85.0) * smooth_zoom
        center = landing_rel + (0.32 + 0.13 * smooth_zoom) * remaining
        ax.set_xlim(center[0] - view_radius, center[0] + view_radius)
        ax.set_ylim(center[1] - view_radius, center[1] + view_radius)
        ax.set_zlim(center[2] - view_radius, center[2] + view_radius)

        body, nose, _ = rocket_mesh(p, axis, rocket_length, rocket_radius)
        Xb, Yb, Zb = body
        Xn, Yn, Zn = nose
        body_artist = ax.plot_surface(Xb, Yb, Zb, alpha=0.98, linewidth=0, antialiased=False)
        nose_artist = ax.plot_surface(Xn, Yn, Zn, alpha=0.98, linewidth=0, antialiased=False)
        dynamic_artists.extend([body_artist, nose_artist])

        add_thrust_visuals(
            ax, p, thrust_vec, axis,
            rocket_length, rocket_radius, ti,
            dynamic_artists,
            arrow_scale=1.8,
            flame_scale=1.5,
            min_arrow_fraction=0.24,
        )

        progress_line.set_data(R_rel[0, :frame_idx + 1], R_rel[1, :frame_idx + 1])
        progress_line.set_3d_properties(R_rel[2, :frame_idx + 1])
        spacecraft_point.set_data([p[0]], [p[1]])
        spacecraft_point.set_3d_properties([p[2]])

        speed_ms = np.linalg.norm(v_rel) * 1000.0
        altitude_km = max(np.dot(n_land, R_abs[:, frame_idx] - (moon_anim[:, frame_idx] + R_M * n_land)), 0.0)
        thrust_kn = np.linalg.norm(thrust_vec)

        ax.set_title(
            "Lunar descent — landing-site tracking view\n"
            f"elapsed={(ti - t_start) / 60.0:.1f} min | "
            f"alt={altitude_km:.2f} km | speed={speed_ms:.2f} m/s | "
            f"thrust={thrust_kn:.1f} kN | mass={M_anim[frame_idx]:.0f} kg | "
            f"prop={prop_anim[frame_idx]:.0f} kg"
        )

        return [progress_line, spacecraft_point, landing_marker, *dynamic_artists]

    anim = FuncAnimation(
        fig,
        update,
        frames=len(animation_time),
        interval=1000.0 / ANIMATION_FPS,
        blit=False,
        repeat=False,
    )
    return fig, anim


# =============================================================================
# 26. LANDING-SITE LOCAL ENU + FIXED CAMERA ANIMATION
# =============================================================================


def create_landing_local_animation():
    """
    Unified lunar powered-descent and landing view from the surface.

    The animation begins at the descent gate and follows the vehicle all the
    way to touchdown.  A smooth landing-site tracking zoom replaces the old
    separate Moon-context descent camera.

    Local coordinates:
        X = East [km]
        Y = North [km]
        Z = Up / altitude [km]
    """
    # Use the complete powered-descent interval; this view now also covers the
    # portion previously shown by the separate Moon-context camera.
    descent_time = TIME[K_DESCENT_START:]

    e_up = unit_vector(n_land)
    e_east = unit_vector(t_land)
    e_north = unit_vector(np.cross(e_up, e_east))
    B = np.vstack([e_east, e_north, e_up])

    t_start = float(descent_time[0])
    animation_time = np.linspace(t_start, T_TOTAL, LANDING_FRAMES)

    R_abs = interp_rows(R_solution, TIME, animation_time)
    V_abs = interp_rows(V_solution, TIME, animation_time)
    T_abs = interp_rows(T_solution, TIME[:-1], animation_time)
    moon_anim = interp_rows(moon_positions, TIME, animation_time)
    M_anim = interp_rows(M_solution, TIME, animation_time)
    prop_anim = np.interp(animation_time, TIME, PROP_CUM_NODES)
    moon_vel = np.vstack([moon_state(t)[1] for t in animation_time]).T

    local_pos = np.zeros_like(R_abs)
    local_vel = np.zeros_like(V_abs)
    local_thrust = np.zeros_like(T_abs)

    for i in range(len(animation_time)):
        landing_abs_i = moon_anim[:, i] + R_M * n_land
        local_pos[:, i] = B @ (R_abs[:, i] - landing_abs_i)
        local_vel[:, i] = B @ (V_abs[:, i] - moon_vel[:, i])
        local_thrust[:, i] = B @ T_abs[:, i]

    # ------------------------------------------------------------------
    # Initial field of view contains the entire powered descent.  update()
    # progressively tightens it around the vehicle and landing site.
    # ------------------------------------------------------------------
    max_x = max(float(np.max(np.abs(local_pos[0]))), 3.0)
    max_y = max(float(np.max(np.abs(local_pos[1]))), 3.0)
    max_alt = max(float(np.max(local_pos[2])), 5.0)

    x_half = 1.20 * max_x
    y_half = 1.20 * max_y
    z_top = 1.08 * max_alt
    z_bottom = -0.05

    # Keep a little surface context even for a nearly vertical solution.
    x_half = max(x_half, 8.0)
    y_half = max(y_half, 8.0)
    z_top = max(z_top, GROUND_VIEW_START_ALT_KM * 1.02)

    patch_half = max(15.0, 1.15 * max(x_half, y_half))
    Xs, Ys, Zs = lunar_surface_patch(patch_half, n=65)

    fig = plt.figure(figsize=(11.5, 8.5))
    ax = fig.add_subplot(111, projection="3d")

    # The landing-site tangent plane is the visual floor at local Z=0.  This
    # matches the altitude and landing-cone constraints used by the optimizer.
    ax.plot_surface(
        Xs, Ys, Zs,
        color="#777777",
        alpha=0.78,
        edgecolor="#9a9a9a",
        linewidth=0.22,
        antialiased=True,
        shade=True,
    )

    # Entire final landing path is shown faintly as context.
    ax.plot(
        local_pos[0], local_pos[1], local_pos[2],
        linewidth=1.1,
        alpha=0.22,
        label="Final landing trajectory",
    )

    progress_line, = ax.plot([], [], [], linewidth=2.8, label="Flight path")
    spacecraft_point, = ax.plot([], [], [], marker="o", markersize=4, linestyle="None")
    landing_marker, = ax.plot(
        [0.0], [0.0], [0.0],
        marker="*", markersize=14, linestyle="None", label="Landing site"
    )

    # A small landing-pad ring on the surface makes touchdown easy to see.
    pad_theta = np.linspace(0.0, 2.0 * np.pi, 100)
    pad_r = min(0.8, 0.06 * max(x_half, y_half))
    ax.plot(
        pad_r * np.cos(pad_theta),
        pad_r * np.sin(pad_theta),
        np.zeros_like(pad_theta),
        linewidth=1.5,
        label="Landing pad",
    )

    # Landing cone constraint shown as a wireframe corridor.  Feasible vehicle
    # positions lie inside this cone: horizontal error <= tan(angle) * altitude.
    guide_alt = np.linspace(0.0, z_top, 60)
    guide_rad = np.tan(LANDING_CONE_ANGLE) * guide_alt
    guide_mask = guide_rad <= 0.95 * max(x_half, y_half)
    guide_alt = guide_alt[guide_mask]
    guide_rad = guide_rad[guide_mask]
    if len(guide_alt) > 1:
        cone_theta = np.linspace(0.0, 2.0 * np.pi, 25)
        cone_R, cone_Theta = np.meshgrid(guide_rad, cone_theta)
        cone_Z = np.broadcast_to(guide_alt, cone_R.shape)
        ax.plot_wireframe(
            cone_R * np.cos(cone_Theta),
            cone_R * np.sin(cone_Theta),
            cone_Z,
            rstride=4,
            cstride=10,
            color="tab:orange",
            linewidth=0.65,
            alpha=0.32,
            label=f"Landing cone ({np.degrees(LANDING_CONE_ANGLE):.0f} deg)",
        )

    # ------------------------------------------------------------------
    # Ground observer camera.
    # Low elevation makes the scene look from near the lunar surface rather
    # than from above.  This stays unchanged for the whole animation.
    # ------------------------------------------------------------------
    initial_horizontal = local_pos[:2, 0]
    if np.linalg.norm(initial_horizontal) > 1.0e-8:
        approach_azimuth = np.degrees(np.arctan2(initial_horizontal[1], initial_horizontal[0]))
        camera_azim = approach_azimuth + 155.0
    else:
        camera_azim = -55.0

    ax.view_init(elev=18.0, azim=camera_azim)
    ax.set_proj_type("persp", focal_length=0.9)

    ax.set_xlim(-x_half, x_half)
    ax.set_ylim(-y_half, y_half)
    ax.set_zlim(z_bottom, z_top)
    ax.set_box_aspect((2.0 * x_half, 2.0 * y_half, 1.45 * z_top))
    ax.zaxis.set_pane_color((0.0, 0.0, 0.0, 0.0))

    ax.set_xlabel("Local East [km]")
    ax.set_ylabel("Local North [km]")
    ax.set_zlabel("Altitude [km]")
    ax.legend(loc="upper left")

    telemetry = ax.text2D(
        0.02, 0.02, "",
        transform=ax.transAxes,
        va="bottom",
        family="monospace",
    )

    fixed_camera_note = ax.text2D(
        0.71, 0.02,
        "POWERED DESCENT + LANDING\nTRACKING GROUND CAMERA",
        transform=ax.transAxes,
        va="bottom",
        ha="left",
        family="monospace",
    )

    dynamic_artists = []

    def clear_dynamic():
        while dynamic_artists:
            artist = dynamic_artists.pop()
            try:
                artist.remove()
            except (ValueError, AttributeError):
                pass

    # Rocket display size is fixed for the whole ground-view clip.
    rocket_length = float(np.clip(0.055 * z_top, 0.75, 1.75))
    rocket_radius = 0.17 * rocket_length

    def update(frame_idx):
        clear_dynamic()

        ti = animation_time[frame_idx]
        p = local_pos[:, frame_idx]
        v = local_vel[:, frame_idx]
        thrust_vec = local_thrust[:, frame_idx]
        body_axis = unit_vector(thrust_vec, fallback=-v)

        # Keep both vehicle and landing point in frame, then smoothly tighten
        # to the flat lunar floor as the remaining distance approaches zero.
        remaining_distance = float(np.linalg.norm(p))
        initial_distance = max(float(np.linalg.norm(local_pos[:, 0])), 1.0)
        zoom_fraction = np.clip(remaining_distance / initial_distance, 0.0, 1.0)

        # Hold the wide composition longer.  The previous smoothstep closed in
        # too quickly and could crop the vehicle above the frame during lunar
        # arrival.  The square root gives more screen space through mid-descent.
        smooth_zoom = np.sqrt(zoom_fraction)
        view_half = 8.0 + (max(x_half, y_half) - 8.0) * smooth_zoom
        view_half = max(view_half, 0.78 * np.linalg.norm(p[:2]) + 2.0)
        view_center_xy = (0.32 + 0.13 * smooth_zoom) * p[:2]
        view_top = 5.0 + (z_top - 5.0) * smooth_zoom
        view_top = max(view_top, 1.18 * max(p[2], 0.0) + 2.0)
        ax.set_xlim(view_center_xy[0] - view_half, view_center_xy[0] + view_half)
        ax.set_ylim(view_center_xy[1] - view_half, view_center_xy[1] + view_half)
        ax.set_zlim(z_bottom, view_top)
        ax.set_box_aspect((2.0 * view_half, 2.0 * view_half, 1.45 * view_top))
        camera_elev = 8.0 + 10.0 * smooth_zoom
        ax.view_init(elev=camera_elev, azim=camera_azim)

        body, nose, _ = rocket_mesh(p, body_axis, rocket_length, rocket_radius)
        Xb, Yb, Zb = body
        Xn, Yn, Zn = nose

        body_artist = ax.plot_surface(
            Xb, Yb, Zb,
            alpha=0.98,
            linewidth=0,
            antialiased=False,
        )
        nose_artist = ax.plot_surface(
            Xn, Yn, Zn,
            alpha=0.98,
            linewidth=0,
            antialiased=False,
        )
        dynamic_artists.extend([body_artist, nose_artist])

        # +T arrow and -T exhaust flame.  Their DISPLAY scale varies with
        # thrust magnitude, but the camera and axes do not move.
        add_thrust_visuals(
            ax,
            p,
            thrust_vec,
            body_axis,
            rocket_length,
            rocket_radius,
            ti,
            dynamic_artists,
            arrow_scale=2.4,
            flame_scale=2.5,
            min_arrow_fraction=0.22,
        )

        progress_line.set_data(
            local_pos[0, :frame_idx + 1],
            local_pos[1, :frame_idx + 1],
        )
        progress_line.set_3d_properties(local_pos[2, :frame_idx + 1])
        spacecraft_point.set_data([p[0]], [p[1]])
        spacecraft_point.set_3d_properties([p[2]])

        thrust_kn = np.linalg.norm(thrust_vec)
        speed_ms = np.linalg.norm(v) * 1000.0
        horizontal_ms = np.linalg.norm(v[:2]) * 1000.0
        vertical_ms = v[2] * 1000.0
        altitude_km = max(p[2], 0.0)
        horizontal_km = np.linalg.norm(p[:2])
        cone_limit_km = np.tan(LANDING_CONE_ANGLE) * altitude_km
        cone_margin_km = cone_limit_km - horizontal_km

        descent_frac = np.clip(
            (ti - TIME[K_DESCENT_START])
            / max(T_TOTAL - TIME[K_DESCENT_START], 1.0),
            0.0,
            1.0,
        )
        speed_limit_ms = (
            2.5 * (1.0 - descent_frac)**1.3 + 0.030
        ) * 1000.0
        if descent_frac >= 0.75:
            terminal_frac = (descent_frac - 0.75) / 0.25
            down_limit_ms = (
                0.080 * (1.0 - terminal_frac) + TOUCHDOWN_SPEED_MAX
            ) * 1000.0
            horizontal_limit_ms = (
                0.050 * (1.0 - terminal_frac) + TOUCHDOWN_HORIZONTAL_MAX
            ) * 1000.0
        else:
            down_limit_ms = speed_limit_ms
            horizontal_limit_ms = speed_limit_ms

        cone_ok = cone_margin_km >= -1.0e-6
        speed_ok = speed_ms <= speed_limit_ms + 1.0e-6
        terminal_ok = (
            -vertical_ms <= down_limit_ms + 1.0e-6
            and horizontal_ms <= horizontal_limit_ms + 1.0e-6
        )

        # Ring at the current altitude makes the instantaneous position bound
        # readable without having to infer it from the full cone wireframe.
        if cone_limit_km <= 1.5 * max(x_half, y_half):
            ring_theta = np.linspace(0.0, 2.0 * np.pi, 80)
            constraint_ring, = ax.plot(
                cone_limit_km * np.cos(ring_theta),
                cone_limit_km * np.sin(ring_theta),
                np.full_like(ring_theta, altitude_km),
                color="tab:green" if cone_ok else "tab:red",
                linewidth=1.8,
                alpha=0.85,
            )
            dynamic_artists.append(constraint_ring)

        telemetry.set_text(
            f"elapsed       {(ti - t_start):8.1f} s\n"
            f"altitude      {altitude_km:8.3f} km\n"
            f"horizontal    {horizontal_km:8.3f} km\n"
            f"speed         {speed_ms:8.2f} m/s\n"
            f"horizontal v  {horizontal_ms:8.2f} m/s\n"
            f"vertical v    {vertical_ms:8.2f} m/s\n"
            f"thrust        {thrust_kn:8.2f} kN\n"
            f"cone margin   {cone_margin_km:8.3f} km  {'OK' if cone_ok else 'VIOL'}\n"
            f"speed limit   {speed_limit_ms:8.2f} m/s  {'OK' if speed_ok else 'VIOL'}\n"
            f"down limit    {down_limit_ms:8.2f} m/s\n"
            f"horiz limit   {horizontal_limit_ms:8.2f} m/s  "
            f"{'OK' if terminal_ok else 'VIOL'}\n"
            f"mass          {M_anim[frame_idx]:8.0f} kg\n"
            f"propellant    {prop_anim[frame_idx]:8.0f} kg"
        )

        ax.set_title(
            "Lunar powered descent + landing — ground tracking view\n"
            "flat surface | arrow = +thrust | flame = exhaust (-thrust)"
        )

        return [
            progress_line,
            spacecraft_point,
            landing_marker,
            telemetry,
            fixed_camera_note,
            *dynamic_artists,
        ]

    anim = FuncAnimation(
        fig,
        update,
        frames=len(animation_time),
        interval=1000.0 / ANIMATION_FPS,
        blit=False,
        repeat=False,
    )
    return fig, anim


# =============================================================================
# 27. GENERATE MATPLOTLIB ANIMATIONS
# =============================================================================


def create_static_mission_summary():
    """Create one top-down transfer and side-view landing constraint figure."""
    fig, (ax_transfer, ax_landing) = plt.subplots(
        1, 2, figsize=(18, 8.5), constrained_layout=True,
    )

    # ------------------------------------------------------------------
    # Left: top-down Earth-to-Moon navigation with sampled thrust vectors.
    # ------------------------------------------------------------------
    ax_transfer.plot(
        R_solution[0], R_solution[1],
        linewidth=2.2, label="Optimized spacecraft path",
    )
    ax_transfer.plot(
        moon_positions[0], moon_positions[1],
        linestyle="--", linewidth=1.1, label="Moon path",
    )
    earth_display_radius = max(R_E, 0.025 * D_EM)
    moon_display_radius = max(R_M, 0.018 * D_EM)
    ax_transfer.add_patch(plt.Circle(
        (0.0, 0.0), earth_display_radius,
        alpha=0.50, hatch="///", label="Earth (display size exaggerated)",
    ))
    ax_transfer.add_patch(plt.Circle(
        (moon_positions[0, -1], moon_positions[1, -1]),
        moon_display_radius, alpha=0.70, hatch="...",
        label="Moon (display size exaggerated)",
    ))
    ax_transfer.scatter(
        [R_solution[0, 0]], [R_solution[1, 0]],
        marker="o", s=45, zorder=6, label="Mission start",
    )
    ax_transfer.scatter(
        [R_solution[0, -1]], [R_solution[1, -1]],
        marker="*", s=130, zorder=7,
        label="Landing",
    )

    def sampled_active_indices(start, stop, count):
        candidates = np.arange(start, min(stop, N))
        active = candidates[np.linalg.norm(T_solution[:, candidates], axis=0) > 1.0e-6]
        if len(active) <= count:
            return active
        pick = np.linspace(0, len(active) - 1, count).round().astype(int)
        return active[pick]

    overview_groups = [
        ("TLI thrust", K_TLI_START, K_TRANSFER_START, 6),
        ("MCC thrust", K_TRANSFER_START, K_DESCENT_START, 10),
        ("Descent thrust", K_DESCENT_START, N, 7),
    ]
    for label, start, stop, count in overview_groups:
        indices = sampled_active_indices(start, stop, count)
        first = True
        for k in indices:
            direction_xy = T_solution[:2, k]
            norm_xy = np.linalg.norm(direction_xy)
            if norm_xy < 1.0e-9:
                continue
            frac = thrust_fraction(T_solution[:, k], TIME[k])
            arrow_length = D_EM * (0.020 + 0.030 * frac)
            delta = arrow_length * direction_xy / norm_xy
            ax_transfer.annotate(
                "",
                xy=R_solution[:2, k] + delta,
                xytext=R_solution[:2, k],
                arrowprops=dict(
                    arrowstyle="-|>", lw=1.5,
                    mutation_scale=11, alpha=0.88,
                ),
            )
            if first:
                ax_transfer.plot([], [], linewidth=2.0, label=label)
                first = False

    ax_transfer.set_title("Earth → Moon navigation (top-down 2-D)")
    ax_transfer.set_xlabel("Earth-centered X [km]")
    ax_transfer.set_ylabel("Earth-centered Y [km]")
    ax_transfer.set_aspect("equal", adjustable="box")
    ax_transfer.grid(alpha=0.24)
    ax_transfer.legend(loc="best", fontsize=8)

    # ------------------------------------------------------------------
    # Right: local landing side view, thrust vectors, and active constraints.
    # ------------------------------------------------------------------
    e_up = unit_vector(n_land)
    e_downrange = unit_vector(t_land)
    descent_indices = np.arange(K_DESCENT_START, N + 1)
    downrange = np.zeros(len(descent_indices))
    altitude = np.zeros(len(descent_indices))
    constraint_ok = np.ones(len(descent_indices), dtype=bool)

    for i, k in enumerate(descent_indices):
        r_moon_k, v_moon_k = moon_state(TIME[k])
        landing_k = r_moon_k + R_M * n_land
        delta_r = R_solution[:, k] - landing_k
        v_rel = V_solution[:, k] - v_moon_k
        downrange[i] = e_downrange @ delta_r
        altitude[i] = e_up @ delta_r
        horizontal = np.linalg.norm(P_HORIZONTAL @ delta_r)
        frac = (k - K_DESCENT_START) / max(1, N - K_DESCENT_START)
        vmax = 2.5 * (1.0 - frac)**1.3 + 0.030
        low_alt_horizontal_limit = (
            TOUCHDOWN_HORIZONTAL_MAX
            + LOW_ALT_HORIZONTAL_SPEED_SLOPE * max(altitude[i], 0.0)
        )
        constraint_ok[i] = (
            altitude[i] >= -1.0e-6
            and horizontal <= np.tan(LANDING_CONE_ANGLE) * max(altitude[i], 0.0) + 1.0e-6
            and np.linalg.norm(v_rel) <= vmax + 1.0e-6
            and (e_up @ v_rel) <= 1.0e-8
        )
        if frac >= 0.75:
            constraint_ok[i] &= (
                np.linalg.norm(P_HORIZONTAL @ v_rel)
                <= low_alt_horizontal_limit + 1.0e-8
            )
        if frac >= TERMINAL_CONE_START_FRACTION:
            constraint_ok[i] &= (
                horizontal
                <= np.tan(TERMINAL_LANDING_CONE_ANGLE)
                * max(altitude[i], 0.0) + 1.0e-6
            )

    constraint_ok[1:] &= np.diff(altitude) <= 1.0e-8

    max_alt = max(float(np.max(altitude)), 1.0)
    cone_alt = np.linspace(0.0, max_alt, 200)
    cone_edge = np.tan(LANDING_CONE_ANGLE) * cone_alt
    ax_landing.fill_betweenx(
        cone_alt, -cone_edge, cone_edge,
        alpha=0.12, label="Allowed landing cone",
    )
    ax_landing.plot(cone_edge, cone_alt, "--", linewidth=1.2)
    ax_landing.plot(-cone_edge, cone_alt, "--", linewidth=1.2)
    terminal_cone_edge = np.tan(TERMINAL_LANDING_CONE_ANGLE) * cone_alt
    ax_landing.plot(
        terminal_cone_edge, cone_alt, ":", linewidth=1.4,
        label=f"Terminal cone ({np.degrees(TERMINAL_LANDING_CONE_ANGLE):.0f} deg)",
    )
    ax_landing.plot(-terminal_cone_edge, cone_alt, ":", linewidth=1.4)
    surface_half = max(float(np.max(np.abs(downrange))) * 1.15, 10.0)
    ax_landing.plot(
        [-surface_half, surface_half], [0.0, 0.0],
        linewidth=5.0, solid_capstyle="butt", label="Flat lunar surface",
    )
    ax_landing.plot(
        downrange, altitude, linewidth=2.5,
        label="Optimized landing trajectory",
    )
    ax_landing.scatter(
        downrange[constraint_ok], altitude[constraint_ok],
        s=14, marker="o", zorder=5, label="Constraints satisfied",
    )
    if np.any(~constraint_ok):
        ax_landing.scatter(
            downrange[~constraint_ok], altitude[~constraint_ok],
            s=28, marker="x", zorder=6, label="Constraint violation",
        )

    landing_thrust_indices = sampled_active_indices(K_DESCENT_START, N, 13)
    landing_arrow_scale = 0.085 * max(max_alt, 2.0 * surface_half)
    for k in landing_thrust_indices:
        i = k - K_DESCENT_START
        tx = e_downrange @ T_solution[:, k]
        tz = e_up @ T_solution[:, k]
        direction = np.array([tx, tz])
        direction_norm = np.linalg.norm(direction)
        if direction_norm < 1.0e-9:
            continue
        frac = thrust_fraction(T_solution[:, k], TIME[k])
        delta = landing_arrow_scale * (0.30 + 0.70 * frac) * direction / direction_norm
        ax_landing.annotate(
            "",
            xy=np.array([downrange[i], altitude[i]]) + delta,
            xytext=np.array([downrange[i], altitude[i]]),
            arrowprops=dict(
                arrowstyle="-|>", lw=1.7,
                mutation_scale=11, alpha=0.90,
            ),
        )
    ax_landing.plot([], [], linewidth=2.0, label="Thrust direction")

    v_touch_rel = V_solution[:, -1] - v_moon_final
    touch_speed = np.linalg.norm(v_touch_rel) * 1000.0
    touch_horizontal = np.linalg.norm(P_HORIZONTAL @ v_touch_rel) * 1000.0
    touch_down = -(n_land @ v_touch_rel) * 1000.0
    ax_landing.text(
        0.02, 0.98,
        "LANDING CONSTRAINTS\n"
        f"cone half-angle: {np.degrees(LANDING_CONE_ANGLE):.0f} deg\n"
        f"terminal cone:   {np.degrees(TERMINAL_LANDING_CONE_ANGLE):.0f} deg\n"
        f"touch speed:     {touch_speed:.2f} / {TOUCHDOWN_SPEED_MAX * 1000.0:.1f} m/s\n"
        f"horizontal:      {touch_horizontal:.2f} / {TOUCHDOWN_HORIZONTAL_MAX * 1000.0:.1f} m/s\n"
        f"downward:        {touch_down:.2f} m/s",
        transform=ax_landing.transAxes, va="top", family="monospace",
        bbox=dict(boxstyle="round", alpha=0.84),
    )
    ax_landing.scatter([0.0], [0.0], marker="*", s=150, zorder=8)
    ax_landing.set_title("Lunar powered descent (local side view)")
    ax_landing.set_xlabel("Downrange [km]")
    ax_landing.set_ylabel("Altitude above flat surface [km]")
    ax_landing.set_ylim(bottom=-0.02 * max_alt)
    ax_landing.grid(alpha=0.24)
    ax_landing.legend(loc="upper right", fontsize=8)

    fig.suptitle(
        "Apollo-like mission: optimized trajectory, thrust program, and landing constraints",
        fontsize=15,
    )
    return fig


def export_static_mission_summary():
    fig = create_static_mission_summary()
    fig.savefig(STATIC_SUMMARY_PNG, dpi=180, bbox_inches="tight")
    print(f"Wrote static mission summary: {STATIC_SUMMARY_PNG}")
    if SHOW_ANIMATION_WINDOW:
        plt.show()
    else:
        plt.close(fig)


def export_combined_mission_animation():
    """Render overview and unified ground descent as one continuous film."""
    if shutil.which("ffmpeg") is None:
        print("ffmpeg not found -> combined mission export skipped")
        return

    scene_factories = [
        ("01_overview.mp4", create_overview_animation),
        ("02_descent_and_landing.mp4", create_landing_local_animation),
    ]

    with tempfile.TemporaryDirectory(prefix="apollo_mission_") as temp_dir:
        temp_path = Path(temp_dir)
        clip_paths = []

        for clip_name, factory in scene_factories:
            fig, anim = factory()
            clip_path = temp_path / clip_name
            write_animation_mp4(anim, str(clip_path), ANIMATION_FPS)
            plt.close(fig)
            clip_paths.append(clip_path)

        concat_list = temp_path / "clips.txt"
        concat_list.write_text(
            "".join(f"file '{path.as_posix()}'\n" for path in clip_paths),
            encoding="utf-8",
        )
        subprocess.run(
            [
                "ffmpeg", "-y",
                "-f", "concat",
                "-safe", "0",
                "-i", str(concat_list),
                "-c", "copy",
                str(Path(COMBINED_MP4).resolve()),
            ],
            check=True,
        )

    print(f"Wrote complete mission animation: {COMBINED_MP4}")


def export_matplotlib_animations():
    print("\n================ MISSION VISUALIZATION EXPORT ================")

    if GENERATE_STATIC_SUMMARY:
        export_static_mission_summary()

    if not (GENERATE_COMBINED_MISSION or GENERATE_MPL_MP4 or SHOW_ANIMATION_WINDOW):
        print("Output mode: static PNG only")
        return

    print(f"Animation playback target: {ANIMATION_FPS} FPS")
    print("Thrust visualization: force arrow + exhaust flame enabled")
    print("Landing visualization: lunar ground-observer fixed camera (no zoom) enabled")

    if GENERATE_COMBINED_MISSION:
        print("Output mode: overview -> unified ground descent/landing film")
        export_combined_mission_animation()

    if not (GENERATE_MPL_MP4 or SHOW_ANIMATION_WINDOW):
        return

    overview_fig, overview_anim = create_overview_animation()
    if GENERATE_MPL_MP4:
        write_animation_mp4(overview_anim, OVERVIEW_MP4, ANIMATION_FPS)
    if not SHOW_ANIMATION_WINDOW:
        plt.close(overview_fig)

    descent_fig, descent_anim = create_descent_context_animation()
    if GENERATE_MPL_MP4:
        write_animation_mp4(descent_anim, DESCENT_MP4, ANIMATION_FPS)
    if not SHOW_ANIMATION_WINDOW:
        plt.close(descent_fig)

    landing_fig, landing_anim = create_landing_local_animation()
    if GENERATE_MPL_MP4:
        write_animation_mp4(landing_anim, LANDING_MP4, ANIMATION_FPS)

    if SHOW_ANIMATION_WINDOW:
        plt.show()
    else:
        plt.close(landing_fig)


export_matplotlib_animations()
